opentable/sous

commands/build.go
commands/contracts.go
commands/run.go
commands/test.go
config/structs.go
core/assembly.go
core/context.go
core/detect.go
core/sous.go
core/state.go
core/targets.go
main.go
packs/nodejs/app_target.go
packs/nodejs/compile_target.go
packs/nodejs/nodejs.go
packs/nodejs/nodejs_pack_test.go
packs/nodejs/nodejs_target.go
packs/nodejs/pack.go
packs/nodejs/test_target.go
registry.go
scripts/install-dev
tools/cmd/cmd.go
tools/docker/container.go
tools/docker/docker.go
tools/docker/file.go
tools/docker/run.go
tools/file/cleanup.go

This avoids having production containers with too many dependencies installed, like make, gcc, etc.
Also contains updates to stale build detection, and adds -rebuild and -rebuild-all flags to the build, test, run, and contracts commands.

Compile NodeJS projects in specialise "build" containers

---

sous/manifest.go
util/validator/validator.go
util/validator/validator_test.go

Adds a validation helper using tags to validate non-emptiness and non-zeroness of values.
Also adds `validator.Interface` which can be implemented on any type, and will be run against all instances of that type whether they occur as structs, struct fields, map keys, or slice/map/array/pointer values.

Validation

---

lib/image_mapping.go
lib/image_mapping_test.go
lib/rectifier.go
lib/resolve.go
lib/test/integration_test.go
util/shell/sh.go

If we don't know the image name for a source version, Resolve() (and therefore
`sous rectify`) will exit early rather than attempt a deploy that will then
fail.

Resolve() fail fast

---

ext/storage/storage_test.go
ext/storage/test_data/clusters/cluster-1.yaml
ext/storage/test_data/clusters/other-cluster.yaml
ext/storage/test_data/defs.yaml
lib/state.go
util/hy/context.go

- Using flattened defs file containing all non-manifest data
See comments in DCOPS-7430

Storage: correct hy tags and test data.

---

cli/sous_rectify.go
lib/deployment.go
lib/image_mapping_test.go
lib/rectifier.go
lib/rectifier_test.go
lib/resolve.go

This is effectively "yes merge, but..."
Two variations from your original, @samsalisbury - I created a type for the predicate function, and changed the Deployments.Filter function to return the Deployments itself if the function is nil. Mostly a little efficiency, but I can see the argument for returning a copy. Let me know what you think.

Single manifest

---

lib/actual_deployment_set.go
lib/build_test.go
lib/deployment_builder.go
lib/deployment_diff.go
lib/image_mapping.go
lib/image_mapping_test.go
lib/logging.go
lib/manifest.go
lib/recti-agent.go
lib/rectifier.go
lib/resolve.go
lib/test/deployment_builder_test.go
lib/test/integration_test.go
lib/test/name_cache_test.go
lib/volumes.go
lib/volumes_test.go
util/docker_registry/client.go
vendor/vendor.json

This PR ensures that all docker image names used with Singularity are digest
(aka canonical) names. The result is that Sous can be absolutely certain that
either the image deployed to singularity corresponds to information it has, or
else that knowledge of the contents of that image has been lost. Prior to this,
version tags were being used, which allowed for significant drift without Sous
being aware of a change. As a concequence, the resolution protocol is much more
consistent and should be more robust.
A number of outright errors were uncovered which had been concealed by the
less stable process, including variations in the volume configuration.
Re: image knowledge being lost: it's possible that the tag-name under which a
particular image was pushed would be reused, which would leave …

Significant stabilization of resolution

---

bin/install-dev
cli/sous_init.go
ext/docker/builder.go
ext/otpl/otpl.go
main.go
util/firsterr/firsterr.go
util/firsterr/firsterr_test.go
util/shell/command.go
util/shell/sh.go
util/shell/shell.go
util/shell/test_shell.go

Sous init now takes into account otpl-deploy configuration files (in the form of `config/{cluster}/singularity(-request)?\.json` files. If any such files are present and parseable, the user must explicitly set `-ignore-otpl-deploy` or `-use-otpl-deploy` flags.

Parse OTPL-deploy config

---

cli/rectify_test.go
cli/sous_rectify.go
doc/disjoint-rectification.md
lib/state.go
lib/state_test.go

Adds -cluster flag to restrict rectify to considering only one cluster.
When used, also adds configuration to the GDM to only report that cluster,
so that we save queries targetting other clusters.
Also: renamed "-manifest" to "-repo" and added "-offset" so that manifests can
be properly constrained to.
Finally, adds "-all" because once Sous begins to be used in a "disjoint" mode,
gobal rectifies become hazardous.

Single cluster rectify TECHOPS-108

---

ext/docker/names.go
ext/singularity/actual_deployment_set.go
ext/singularity/deployment_builder.go
ext/singularity/recti-agent.go
lib/logging.go

This is the actual address to Wil Wade's issue
In starting to use pkg/errors, we broke a test of an error type
The root fix is to use errors.Cause() to get the error back out.
There's also some tuning to the ADS code to improve its error reporting

Bugfix: too paranoid

---

cli/cli.go
cli/cli_test.go
cli/graph.go
cli/graph_test.go
cli/sous_build.go
util/cmdr/cli.go

I did notice but don't have time to fix: sous context is broken ATM.
Gist of the fixes:
`sous` was broken by the second invoke: when we invoked the second time on the same CLI,
the Sous command object got added again, which is how it got double-registered.
The address there was to add a new "Startup" hook, which actually creates a new
graph (and chain) for each invocation. I waffled on this for a bit, but the
ultimate argument I came to was that a sequence of invocations within a single
execution should work as much as possible as if the user had run them each from
the command line. I'd be open to re-examining this, but one key observation is
that we invoke commands in order to change the global state, so caching that at
the start of a command sequence is likely to have confusing results. …

Fixes sous, sous build, sous rectify

---

cli/graph.go
ext/storage/disk_state_manager.go
ext/storage/disk_state_manager_test.go
lib/deployments_generated.go
lib/manifests_generated.go
util/blueprints/cmap/cmap.go
util/blueprints/cmap/cmap_test.go
vendor/github.com/opentable/hy/codec.go
vendor/vendor.json

Addresses confusion with nil concurrent maps (now they panic explicitly when not initialised). This had knock-on effects on how we handle empty state directory.

Less confusing concurrent maps.

---

cli/graph.go
ext/storage/disk_state_manager.go
ext/storage/disk_state_manager_test.go
lib/deployments_generated.go
lib/manifests_generated.go
util/blueprints/cmap/cmap.go
util/blueprints/cmap/cmap_test.go
util/firsterr/firsterr.go
util/firsterr/firsterr_test.go
vendor/github.com/opentable/hy/codec.go
vendor/vendor.json

Includes #111 
first err test had a daft data race where a counter was being updated from multiple goroutines at once without any synchronisation. Addressed with atomic.AddInt64.

Fix firsterr test race

---

cli/graph.go
cli/sous.go
cli/sous_deploy_test.go
cli/sous_init.go
lib/map_state_to_deployments.go
lib/map_state_to_deployments_test.go

Includes #123 
'sous init' now ignores any clusters defined in otpl-deploy config that aren't known to sous

Sous init fix

---

ext/docker/builder.go
ext/docker/image_mapping.go
ext/docker/image_mapping_test.go
ext/singularity/dummy_rectification_client.go
ext/singularity/recti-agent.go
ext/storage/testdata/in/defs.yaml
integration/integration_test.go
lib/buildpack.go
lib/dummy_registry.go
lib/registry.go
lib/resolve_errors.go
lib/resolver.go
lib/resolver_test.go
lib/state.go

During resolution, deployments are checked against their build artifacts.
Advisories on the artifacts are compared to a whitelist configured for the
cluster in defs.yaml. If the advisory isn't listed, the deploy fails.

Reject un-accepable advisories on deploy. TECHOPS-485

---

cli/sous_query_adc.go
cli/sous_query_gdm.go
lib/deployment.go
lib/deployment_dumper.go
lib/deployment_dumper_test.go

i.e. makes the output include the cluster name, not the whole cluster
structure.

Fixes output cluster data for queries

---

cli/add_flags.go
cli/cli.go
cli/cli_test.go
cli/flags_otpl.go
cli/graph.go
cli/graph_sourcecontext.go
cli/graph_sourcecontext_test.go
cli/graph_targetmanifest.go
cli/graph_targetmanifest_test.go
cli/graph_test.go
cli/sous_deploy.go
cli/sous_deploy_test.go
cli/sous_init.go
cli/sous_update.go
ext/storage/disk_state_manager.go
util/cmdr/cli.go
util/cmdr/errors.go

Includes #126 
'sous deploy' now calls 'sous init' internally if the target manifest does not exist.
The way this is achieved leaves something to be desired, in that we manually re-read state and re-compute the GDM, but it works and get us closer to our goal.

Sous deploy

---

cli/cli.go
cli/cli_test.go
util/cmdr/errors.go

Stumbled into this as I was working with demo-service

Fixes mute "no such flag" errors

---

cli/cli.go
cli/cli_test.go
lib/build_config.go
lib/build_config_test.go
util/cmdr/errors.go

Otherwise it's almost impossible to effectively use ephemeral tag, because
it's always tag not head as well.

Makes "tag not head" and "ephemeral tag" exclusive of one another

---

cli/flags_source.go
cli/rectify_test.go
cli/sous_update_test.go
ext/docker/builder_test.go
ext/docker/image_mapping.go
ext/docker/image_mapping_test.go
ext/docker/names.go
ext/singularity/deployer.go
ext/singularity/rectifier_test.go
integration/deployment_builder_test.go
lib/deployment.go
lib/deployment_diff_test.go
lib/deployment_test.go
lib/map_state_to_deployments.go
lib/registry_dumper.go
lib/source_context.go
lib/source_context_test.go
lib/source_id.go
lib/source_id_test.go
lib/source_location.go

- SourceID was always this pair conceptually, now the code makes that clear.
- This can be merged as-is, a follow-up PR will remove the SourceID.Location
method, and rename SourceID.SourceLocation to SourceID.Location.

SourceID = (SourceLocation, Version) in code.

---

ext/singularity/rectifier_test.go
lib/source_id.go
lib/source_id_test.go
lib/source_location.go
lib/source_location_test.go

Writing tests for ManifestID/Flavor I noticed that `ParseSourceID(sid.String()) != sid` and that SourceLocation.String() used a colon instead of the default comma separator. This PR addresses those, and a few other issues.

Flavor preparation.

---

cli/add_flags_test.go
cli/flags_source.go
cli/graph.go
cli/graph_sourcecontext.go
cli/graph_sourcecontext_test.go
cli/graph_targetmanifest.go
cli/graph_targetmanifest_test.go
cli/sous_init.go
cli/sous_update.go
cli/sous_update_test.go
ext/singularity/rectifier_test.go
integration/integration_test.go
lib/assemble_test.go
lib/deployment.go
lib/deployment_diff_test.go
lib/manifest.go
lib/manifest_id.go
lib/manifest_id_test.go
lib/manifests_generated.go
lib/map_state_to_deployments.go
lib/map_state_to_deployments_test.go
lib/owner_set.go
lib/source_id.go
lib/source_id_test.go
lib/source_location.go
lib/source_location_test.go

Includes #148 
This PR implements the concept of "Flavor" as part of a manifest's and deployment's ID.
Flavor is a way to multiply deployments of a single codebase per cluster. The name "Flavor" is already in use at OpenTable to describe short strings used for this purpose, so we have kept the name.
The original spec we imagined for ManifestID.String was to use a colon to separate the SourceLocation from the Flavor, however this makes for file paths in the GDM that are difficult to work with (colon being the default path list separator on gnu/linux type operating systems). Therefore, the implementation uses tilde `~` to separate the two. This means that tilde is a special character in Sous, and for now will not be usable in repository names. Follow-up PR coming to make sure we validate …

Flavor implementation.

---

doc/sous0.1.md
ext/singularity/deployer.go
ext/singularity/deployer_test.go
ext/singularity/deployment_builder.go
ext/singularity/recti-agent.go
ext/singularity/rectifier_test.go
version.go

UPDATE: Includes #156 
Adds release notes and bumps version string to 0.1
Once this is merged, it must be tagged `v0.1` in order to tell Travis to create the release binary.

Sous version 0.1

---

ext/singularity/deployer.go
ext/singularity/deployer_test.go
ext/singularity/deployment_builder.go
ext/singularity/recti-agent.go
ext/singularity/rectifier_test.go

Updates Singularity request names to use the form:
SourceLocation:Flavor:ClusterName
With slashes in SourceLocation replaced with greater than signs.

Singularity names

---

bin/test-sample
integration/deployment_builder_test.go
integration/doc.go
integration/docker_helpers.go
integration/integration_test.go
integration/main_test.go
integration/name_cache_test.go

Addresses part of #159. Specifically, implements the advice in
http://peter.bourgon.org/go-in-production/#testing-and-validation so that `go
test` ./... just executes unit tests

Small change to code to humanize things.

---

lib/deployment_diff.go
lib/deployment_diff_test.go
lib/diff_concentrator.go
lib/diff_concentrator_test.go
server/routemap.go
server/routemap_test.go

Using the existing deployment differ: concentrates deployment hunks into
manifest hunks. This is a precursor to doing an HTTP state manager: we'll check
for differences to the local understanding of the GDM, and push those diffs as
PUTs and DELETEs to manifests.

Deployment diff concentrated into manifest diffs

---

graph/graph.go
graph/graph_test.go
lib/diff_concentrator_test.go
test/empty.go
test/http_state_manager_test.go

As now the CLI commands that alter the Sous State now act as HTTP clients of the server transparently.
Still need e.g. `sous rectify` triggers, possibly, hey presto.

Yo creo this completes the `sous build` client, etc.

---

util/shell/command.go
util/shell/sh.go

Upshot should be that any errors out of shell should have command context.
Worst case: no extra information, best case much faster resolution of problems

Using the Dave Cheney errors package in shell/

---

ext/docker/builder.go
ext/docker/image_mapping.go
ext/docker/image_mapping_test.go
graph/graph.go
graph/graph_test.go
lib/buildpack.go
lib/http_name_inserter.go
lib/http_name_inserter_test.go
lib/registry.go
lib/source_id.go
server/handle_artifact.go
server/handle_artifact_test.go
server/handle_gdm.go
server/router.go
server/routes.go
server/routes_test.go

The Docker registry search component needs to be informed by anything that does
`sous build` of the association betwen an image name and the associated source
version (repo,offset,version) triple.  This requirement is the result if how
the Docker v2 registries work. Until now, the assumption was that the server
would be doing the builds, but it's increasingly clear that this won't always
be the case. In line with the HTTPStateManager, this PR adds an "Inserter"
interface, and a second implementation that sends assocations over HTTP to the
server. The existing, direct Sqlite Inserter or the new HTTP Inserter are
selected based on whether a Server URL is configured.
If a Server is configured, the HTTPNameInserter is used transparently by `sous
build` to notify the server of the docker …

Adds a image name inserter interface and HTTP implementation

---

.gitignore
ext/docker/builder_test.go
ext/docker/image_mapping.go
ext/docker/metadataDockerfile.tmpl
ext/docker/templates.go
ext/singularity/deployer.go
ext/storage/disk_state_manager.go
ext/storage/git_state_manager.go
lib/deploy_config.go
lib/deployment_dumper.go
lib/logging.go
lib/map_state_to_deployments.go
lib/map_state_to_deployments_test.go
lib/resolver.go

There's a variety of little fixes in here; some tweaks to how advisories are
rendered and parsed that was preventing rectification on the server.
But the **real** change here, and it was a bear is in the manifest<->deployment
mappings. Because the `Deployments` is a map of pointers to Deployment, when a
`Manifests` was built from it, the step that deleted keys from the `DeploySpec`
in order to fold them out appropriately (i.e. to make sure that the Manifest
doesn't have redundant and eventually stale environment variables), those
deletes were changing the original Deployment DeploySpec. Most of the effort
involved in this PR comes down to tracking down that one fact and making the
one-line change to fix it.
I'd say that what hit us here was (effectively) global mutable state, and that
the …

Fixes missing environment variables

---

lib/resolver.go
lib/resolver_test.go

During every rectify, Resolver checks all the deployments have docker images,
and that the docker images' advisories are acceptable on their target cluster.
If this isn't the case, the resulting errors block the resolve, which is good
because it means that the GDM represents a state that couldn't be successfully
deployed, and it needs to be fixed.
This PR allows for bad deployments when they have 0 instances, since that's
still an acceptable deployment (i.e. it'll succeed) and it lets us keep data in
the GDM, either about bad services until their fixed, or as we start new
services before we have a good build.

Little change to how Resolver checks deployments

---

ext/singularity/deployer.go
ext/singularity/deployer_test.go
ext/singularity/rectifier_test.go
integration/integration_test.go

Includes #193; comments out line deleting Singularity requests.
This is not at all pretty; but I would like to get server back up-and-running ASAP, and people are relying on Sous in production now, so I want to avoid the possibility of catastrophe from this source.
For deleting things, we need to alert the owner of the deleted manifest that they have an unowned request that needs cleaning up, or else they need to add their manifest back.

Do not delete

---

cli/cli_test.go
cli/deploy_filter_flags.go
cli/flags_source_test.go
cli/rectify_test.go
cli/sous_harvest.go
cli/sous_query_ads.go
cli/sous_query_gdm.go
cli/sous_rectify.go
cli/sous_server.go
config/deploy_filter.go
ext/singularity/actual_deployment_set.go
graph/graph.go
graph/graph_test.go
integration/integration_test.go
lib/auto_resolver_test.go
lib/deployment.go
lib/resolver.go
lib/state.go
lib/state_test.go

Turns out, that was the smallest change... after refactoring the cluster
behavior so that it could be pushed up from `sous rectify` and into the graph
package. In theory it should now be even more trivial to add behavior across
commands.
I'm pretty sure, but have not proven, that this also add -dry-run to server,
which could be used as an "audit mode" - the only problem is that the changes
that *should* be made will be reported as happenning, so there's still some
interpretation to do. We could maybe do something to change how those changes
are logged, at which point this becomes, IMO a complete solution for audit
mode.

Adds -cluster to `sous server`

---

ext/singularity/actual_deployment_set.go
ext/singularity/deployer.go
lib/deploy_config.go
lib/deploy_spec.go
lib/deployment.go
lib/deployment_diff.go
lib/diff_concentrator.go
lib/diff_concentrator_test.go
lib/http_state_manager.go
lib/manifest.go
lib/resources.go
lib/source_id.go
test/http_state_manager_test.go

Includes #196 
This PR gives us a stable server for now. It ignores diffs in Owners and Kinds of deployments. See also https://github.com/opentable/sous-gdm-alpha/commit/6b93f9915aaa0b7082736f7ed14f08674c3adaf3 and https://github.com/opentable/sous-gdm-alpha/commit/67c7b73175171e881b7723347e2f52ef0bbf501a
Now we have the server stabilised, we need to address two issues:
1. Ensure owners get written to Singularity (they don't at present)
2. Ensure Kind is always written in the manifests (at present it is always blank)
Once those are done, we can revert https://github.com/opentable/sous/commit/3e339acf441078f58b3992aa1964da5afd5b5d8c

Patch deployment diff

---

ext/storage/disk_state_manager.go
lib/deploy_config.go
lib/deploy_config_test.go
lib/deploy_spec.go
lib/flaw.go
lib/http_state_manager.go
lib/manifest.go
lib/state.go
server/handle_manifest.go

Primarily, the addition here is adding the concept of Validation to States and
their components.  Flawed.Validate() returns a list of Flaws, which can then
each be Flaw.Repaired.
The disk state manager does a full attempt to repair the state on load and
store, so existing GDMs should be fixed up automatically.
The HTTP state manager checks for flaws but rejects changes that would
introduce them, forcing the user to take considered action. Maybe this is worth
relaxing, but I wanted to aviod "fixing" bad input automatically when we have a
human being at hand.
The server component that receives HTTP state manager manifest updates
Validates the manifests, and rejects with 400 if the update is invalid. It does
not, at present, render an error body describing the error, however. I wanted
to …

Rejects null volumes in manifests

---

ext/singularity/deployer.go
ext/singularity/recti-agent.go
ext/singularity/recti-agent_test.go
ext/singularity/rectifier_test.go
lib/dummy_rectification_client.go
lib/owner_set.go
lib/owner_set_test.go

Removes the Scale method, because POSTs to the /api/requests endpoint will
update an existing Singularity Request if one exists.
Adds parameters to the PostRequest methods for the kind and owners list, so
that they can likewise be updated.
All in all, this should close the loop in terms of state we care to record in
Singularity.

Changes to Singularity client

---

cli/cli.go
cli/cli_test.go
cli/deploy_filter_flags.go
cli/sous_init.go
cli/sous_manifest.go
cli/sous_manifest_get.go
cli/sous_manifest_set.go
cli/sous_manifest_test.go
cli/sous_metadata.go
cli/sous_update.go
cli/tests/sous_test.go
cli/tests/terminal.go
graph/graph.go
graph/graph_test.go
graph/sourcecontext_test.go
graph/targetmanifest.go
lib/resolver.go
lib/state_manager.go
main.go
server/handle_manifest_test.go
server/routes_test.go
server/server.go
server/server_test.go
test/http_state_manager_test.go

Git style workflow looks like
```
sous manifest get > tmpfile
$EDITOR tmpfile
sous manifest set < tmpfile
```
(possibly we could build a porcelain for that)
OTPL-style source repo as source of truth:
```
sous manifest set < repo/manifest.yaml
sous deploy
```
Also in this PR: teasing out the dependency cycle between SourceContext and
TargetManifestID in graph/. Solution was a graph-local `SourceContextDiscovery`
type, which can be unwrapped to `GetError()` or `GetContext()` to get the
discovered-or-default SourceContext.

Adds `sous manifest get` and `sous manifest set`

---

lib/resolver.go
lib/state.go

- Resolves TECHOPS-1238
I've found a series of related probable bugs in the way we (rather I :P) have been using the `copy` builtin. I've been using it backwards. The correct usage is `copy(dest, source)`. Going to get more tests in around all the Clone methods soon.

Bugfix: allowed advisories empty strings.

---

ext/docker/dockerfile_buildpack.go
graph/graph.go

- Build offset was not correctly propagated from source context, now it is.
- The Dockerfile buildpack had a silly error preventing it from building with offsets, now it's less silly.

Bugfix build offset

---

util/configloader/configloader.go
util/configloader/configloader_test.go

The use case was to be able to set SOUS_SERVER="" to do local rectifies
occasionally, but have a default server in the config.yaml for most
things.

Allows for ENV set options to be empty

---

cli/cli.go
util/cmdr/errors.go

- Previously every CLI error was logged raw to stdout.
- Now only the top-level error is printed unless the -d flag is set.
- In particular this makes errors happening during injection much
less verbose and more useful to users.
"Top-level" here means the actual error, rather than all the wrapped context added by `errors.Wrap` which isn't useful to end users.

cli: Detailed errors only if -d flag.

---

cli/cli.go
cli/sous_config.go
config/config.go
graph/graph.go
graph/local_config.go
graph/local_config_test.go
util/cmdr/errors.go
util/configloader/configloader.go
util/shell/command.go
util/shell/sh.go

Includes #223 
- Previously config was not validated.
- Now it is validated up-front for most use cases.
- The exception is when running the 'sous config' command, since
this is the command used to fix a broken config.
Specifically addresses https://github.com/opentable/sous/issues/215#issue-190866561

graph + config: Adds basic config validation.

---

cli/cli.go
graph/graph.go
util/cmdr/errors.go
util/shell/command.go
util/shell/sh.go

Includes #222 
- Previously long-running commands produced no output, leading
to an apparent hang.
- Now at the beginning of a long-running command, the command
line is printed, so the user at least knows what is being
attempted.
- This primarily impacts the docker commands for now.

shell: Long-running commands print when starting.

---

cli/cli.go
cli/sous_config.go
cli/sous_init.go
config/config.go
graph/graph.go
graph/local_config.go
graph/local_config_test.go
graph/targetmanifest.go
lib/state.go
util/cmdr/errors.go
util/configloader/configloader.go
util/shell/command.go
util/shell/sh.go

Includes #224 
- Previously sous init had a bug where it produced a single DeploySpec with an empty cluster name.
- Now by default it produces a valid DeploySpec for each cluster.
- Bonus: sous init now takes -cluster flag, and if specified creates a single DeploySpec for that cluster in the new manifest.

sous init: Now creates valid DeploySpecs.

---

cli/sous_query.go

There are bigger problems that need to be addressed with CLI help messages that aren't being printed, but this solves the portion of issue 216 where the sous query help tip gives incorrect information.

Fix sous query help tip.

---

cli/sous.go
cli/tests/sous_test.go
util/cmdr/command.go
util/cmdr/help.go

The help messages embedded in each of the command line utilities are now printing. I removed parseHelp() and the Help struct from cmdr. I removed the Usage() function that gave Help as its receiver. I removed the unused PrintHelp() function. The help string for the top-level sous command was modified to match what the tests expect. Subcommands have individual short descriptions when described in the help message of the parent command. Modified the tests to expect much longer help messages.

Command Help Fixes

---

ext/docker/image_mapping.go
ext/docker/image_mapping_test.go
ext/docker/names.go
graph/graph.go
integration/deployment_builder_test.go
integration/integration_test.go
integration/name_cache_test.go

When the name cache is checked for the image name for a source ID
and there's no image name known,
it gets all tags from an appropriate repo.
If it doesn't know of an appropriate repo,
it now guesses, based on the algorithm that
the docker builder uses to generate a repo.
TECHOPS-1314

Adds "repo guessing" to the docker name cache

---

lib/auto_resolver_test.go
lib/http_state_manager.go
lib/http_state_manager_test.go

This was done to try to address TECHOPS-1316, but once it was completed, could not reproduce an issue.
Nevertheless, the extra output is worthwhile, so I'm issuing this PR for it.

Adds request debug logging for all HSM HTTP traffic

---

cli/cli_test.go
cli/sous_manifest_get.go
cli/sous_manifest_set.go
cli/sous_metadata_get.go
graph/graph.go
lib/resolver.go

Specifically, StateWriter is an interface, which means it needs a wrapper
struct, and the command itself took the bare interface rather than the `graph`
package wrapper. Regression test added to `cli_test.go` and fix made.
Additionally, I realized while testing this that the output for `sous
{manifest,metadata} {set,get}` was incredibly obtuse. This improves on that as
well.

Bugfix manifest set

---

README.md

It was unclear to me that "let sous know that the project exists" meant "will contact the server and perform an operation" instead of "sets up your local Sous client."
Added an explanation how to add or remove deployments with manifest.
Made it clear *before* running sous init how many deployments it would create.

Expanded sous init explanation in README.

---

ext/docker/config.go
ext/docker/image_mapping.go
ext/docker/image_mapping_test.go
graph/graph_test.go
integration/deployment_builder_test.go
integration/integration_test.go
integration/name_cache_test.go

This PR first adds a duplicate (failing) test to demonstrate that we get different results depending on if we get docker image metadata from the cache or not (e5db6c2). Then it demonstrates that one of the assertions in the tests is not satisfiable by commenting it out, making the tests pass (86169bc). Next we change the way semantic versions are compared in cache database queries to align that with the semver spec (fc3cde9). Then we add revision data to the cache via alteration of the text format used (6b279bd). Finally, the broken assertions are reinstated, and the tests pass (3f183be).

Cache fixes

---

ext/otpl/otpl.go
ext/otpl/otpl_test.go

This maps Singularity resource names, as found in OTPL deploy configuration into Sous resource names. The sous resource names are probably less clear than the singularity names [1], however updating those would be a bit more disruptive than just mapping this correctly for now.
[1] From comment I made on private issue tracker:
>Actually, in Sous proper, we should probably have used "numPorts" instead of "ports", as that is used in the Mesos ecosystem to mean a list of specific ports rather than a request for a number of ports assigned by the platform. However, I will refrain from making that change as it would be pretty disruptive.
> Likewise, "memoryMb" is an easier ask than simply "memory", because it has a unit all we need is a float to represent it. "memory" on the other hand has no …

Bugfix otpl field mapping

---

integration/docker_helpers.go
integration/integration_test.go

This PR introduces cluster specification to integration tests, and covers our actually used code paths where we have a single cluster being rectified at a time. The final commit here introduces a failing test that we would expect to pass, however I am leaving this unfixed for now since we aren't using that code path at the moment.
I think what we may have really done is reveal a design smell, and the best option may be to limit the RunningDeployments call to a single cluster at a time. Or maybe we just need to fix it the way it is? TBD. I consider this PR ready to merge.

Bugfix Cluster Confusion test

---

integration/docker_helpers.go
integration/integration_test.go

Includes #249 because it would result in merge conflicts otherwise.
**UPDATE: Note that only the last two commits in the PR are new (e5b80bc and 2b32d5f)**
Addresses issue noted in https://github.com/opentable/sous/pull/246#discussion_r92236804 where we had a duplicated test that additionally relied on lack of isolation between tests for the intended failure condition to cause a failure. Now the failure condition will hold even when separate `Test` functions are completely isolated.

Test stability (follow up from cluster-confusion test).

---

README.md
ext/storage/git_state_manager.go
ext/storage/git_state_manager_test.go

Sketchy quickfix which should now be (properly) handled by our sous-server
wrapper conflicting with my git config in testing

Changes to Git configuration lookup

---

cli/sous_init.go
graph/sourcecontext_test.go
graph/targetmanifest.go

This more completely explains the requirements to run sous init. Previously it was not explained that the current working directory must not only contain a git repository, but a git repository with configured remotes.

sous init help fix

---

cli/sous_metadata.go
cli/sous_metadata_get.go
cli/sous_metadata_set.go

Added more help text to the "sous metadata" command. Fixed the bugs that kept "sous help metadata get" and "sous help metadata set" help text from printing.

"sous help metadata" fixes

---

cli/cli_test.go
cli/sous_query_artifacts.go
cli/sous_server_test.go

When the DryRunOption was added, `sous query artifacts` got missed. I found a
test that had been commented out from before that time, which is probably why
we had this issue.
DryRunOption became an input to the (docker) Registry injection - in certain
circumstances, a dummy registry gets injected. Because `s q a` doesn't update
the registry, I'm simply injecting a fixed "DryRunNeither" so that a live
registry client becomes available.
Along with this change, I ran across a couple of other places where local git
configuration impacted testing. Tried a different approach to addressing that.
Not sure which I like better.

Fixes a DI oversight in `sous query artifacts`

---

README.md

- Sous' concept of 'cluster' is distinct from that of Mesos,
a single Mesos cluster can host an arbitrary number of Sous
clusters.
- This is a minimal correction by removing 'Mesos' without adding
an explanation of what 'cluster' means in Sous.

README: Remove references to 'Mesos' clusters.

---

util/cmdr/cli.go

I didn't see this being used anywhere, and my local cmdr tests pass without it. This should be an easy merge so long as Travis has no complaints.

Removed unused AddGlobalFlagSetFunc() from cmdr

---

cli/sous_server.go
ext/singularity/deployer.go
ext/singularity/rectifier_test.go
lib/auto_resolver.go
lib/deployer.go
lib/name_resolver.go
lib/resolver.go
lib/resolvestatus.go
lib/resolvestatus_test.go
server/handle_status.go
server/server.go

Includes #269
Makes the result of `AutoResolver.Status()` available in the server at `/status`.
Next step is to make the list of actions taken so far in `ResolveStatus.Log` available to the `/status` endpoint.

Status endpoint3

---

cli/cli.go
cli/sous.go
cli/sous_build.go
cli/sous_config.go
cli/sous_deploy.go
cli/sous_help.go
cli/sous_init.go
cli/sous_manifest.go
cli/sous_manifest_get.go
cli/sous_manifest_set.go
cli/sous_metadata.go
cli/sous_metadata_get.go
cli/sous_metadata_set.go
cli/sous_query.go
cli/sous_query_ads.go
cli/sous_query_gdm.go
cli/sous_rectify.go
cli/sous_update.go
cli/sous_version.go

Aliasing cmdr functions in the cli package have made it more confusing for me to reason about the boundaries between the two.
This PR removes the func aliases (some were going unused) and changes the appearances of cmdr functions within the cli package to be represented more explicitly.
This has been valuable for me just as an exercise. I think it will help things for me and others approaching this codebase in the future, but I am aware that this may be more style than substance. I'm happy to answer any questions, but this PR is the sum of my argument. If this change is problematic feel free to close the ticket.

Remove simple cmdr func aliases from cli package.

---

cli/add_flags_test.go
cli/deploy_filter_flags.go
cli/flags.go

This PR removes the unprinted extended help text from the deploy flags. I changed the short description of a couple of flags to use more concise text from the excised long help.

Remove unparsed extended help text

---

lib/auto_resolver.go
lib/auto_resolver_test.go
lib/resolver.go
lib/resolvestatus.go
lib/resolvestatus_test.go
server/handle_status.go
server/handle_status_test.go

This adds 'GET /status' that can be queried to get: the current GDM, the last stable resolve status (i.e. at the end of a resolve cycle) and the current (in progress) resolve status.
This should be enough data that clients can poll it for updates. If load is unacceptable, we can add a variation that omits the live status and rely on etagging for caching.

Adding /status endpoint

---

server/handle_servers.go
server/handle_servers_test.go
server/server.go

In the future, we'll likely want to give cluster names to the returned
servers. We can change the configs pretty easily, but the deployed
client base will be harder to change. Wrapping the URL string in a
struct (-> a JSON object) lets us add e.g. a Name field when that's
needed.

Future-proofing the /servers API

---

cli/cli_test.go
cli/sous_plumbing.go
cli/sous_plumbing_status.go
cli/sous_server.go
cli/tests/sous_test.go
graph/graph.go
graph/graph_test.go
lib/auto_resolver_test.go
lib/http_state_manager.go
lib/http_state_manager_test.go
lib/httpclient.go
lib/readdebugger.go
lib/resolvefilter.go
lib/resolver.go
lib/status_poller.go
lib/status_poller_test.go
server/handle_manifest.go
server/handle_status.go
server/router.go
server/server.go
test/http_state_manager_test.go

Includes #278; fixes compilation and tests.
- Note: newHTTPClient can now return (nil, nil), meaning no error and a nil
HTTP client) which is unusual in our graph that tends to return an error
when it cannot construct a requested value.
- This is not a problem currently, and it's documented, but we need to take
care when we want to assume the presence of an HTTP client.
**UPDATED** now also fixes invocation of `sous plumbing status` when `config.Server == ""` and adds regression test.

Sous status (fixes compilation + test for #278)

---

lib/httpclient.go
lib/status_poller.go
server/handle_servers_test.go

This is a followup to suggestions made in #282.
The logging of request and response bodies in the HTTP client has been
extracted to a method, and it now logs problems compacting JSON (which can
occur, if nothing else, if a large JSON body comes in in multiple chunks.)
The Ticker leak is now covered with a defer - n.b. that the original NewTicker
was introduced to cover a leak that time.Tick() introduces.

Small code improvements

---

README.md
graph/graph.go
graph/local_config.go
server/handle_servers.go
server/routemap.go
server/server_injection_test.go

The ServerListHandler needs a *config.Config injected, but the graph
didn't have one added (there was a *graph.LocalSousConfig that needed
unwrapping.)
Also adds the start of tests for this kind of case.

Fixes a missed stitch in injection

---

cli/cli.go
cli/cli_test.go
cli/sous_server.go
graph/graph.go
lib/auto_resolver.go
server/graph.go
server/handle_gdm.go
server/handle_gdm_test.go
server/handle_servers.go
server/server.go
server/server_injection_test.go
server/server_test.go
server/statusmiddleware.go
test/http_state_manager_test.go
vendor/github.com/samsalisbury/psyringe/ctor.go
vendor/github.com/samsalisbury/psyringe/psyringe.go
vendor/vendor.json

The proximate cause was the the AutoResolver that `sous server` starts *was
not* the AutoResolver that the StatusHandler queried to get its status fields.
The cause of that was that Psyringe treats cloning as a horizon for all
constructed values: the cloned version will build brand new instances of
everything. This PR includes a vendored-in version of psyringe that changes
that behavior. That version is in a PR to that project.
A consequence of the change was that the (afaik accidental) use of that
.Clone() semantic to get a fresh GDM per request needed to be replaced with an
explicit server-local Add() of a new LiveGDM type.

Fix for null fields in /status

---

ext/docker/image_mapping.go
ext/singularity/actual_deployment_set.go
ext/storage/disk_state_manager.go
lib/deployable_chans.go
lib/deployment_diff.go

These are incidental but hopefully useful refactorings made whilst hunting down a bug with `GetArtifact` not being called for deployments in certain clusters.

Bunch of refactorings working on a bug.

---

cli/cli.go
cli/cli_test.go
cli/sous_update.go
graph/graph.go
lib/logging.go

I couldn't reproduce the issue described in a test - if you note the tests
added to cli_test.go, you'll see that testing with and without -repo produces
the expected behavior.
Along the way I noted that `sous update` (which should perhaps properly be
moved to `plumbing`) will automatically perform a manifest creation, in a way
that is similar to, but separate from `sous init`. Given that manifests cannot
be deleted (at the moment, it's a git operation that requires rebooting all the
running sous servers), creating them automatically seems like a problem to me.
I've removed that option, with a warning to `sous init.`
Finally, I started to see how the StatusPoller doesn't quite align with other
tools that read from the git context. This bears more discussion, but part of
the upshot is that …

Sous deploy -repo tag

---

cli/cli_test.go
cli/sous_deploy.go
cli/sous_update.go
graph/targetmanifest.go
graph/targetmanifest_test.go
lib/status_poller_test.go
test/http_state_manager_test.go

Consequent to changes in the way otpl flags are processed,
newTargetManifest could (effectively) return a nil Manifest. None of its
consumers expect this behavior, so I'm reverting it, ensuring that an
empty Manifest (with default DeploySpecs) is always returned.

Undoing nil Manifest from newManifest

---

cli/cli_test.go
cli/sous_update.go
cli/sous_update_test.go
graph/graph.go
graph/sourcecontext_test.go
graph/targetmanifest.go
graph/testsupport.go
lib/auto_resolver.go
lib/http_state_manager.go
lib/httpclient.go
lib/source_context.go
lib/status_poller.go
server/handle_gdm.go
server/handle_status.go
server/handle_status_test.go
server/server_injection_test.go
server/server_test.go

(sorry this is scattered - juggling with office work & meetings)
sous update, if run in a properly tagged workspace, no longer requires a
-tag or -repo flags.
A significant issue with status polling is fixed: the status endpoint
handler reports the GDM as known to the AutoResolver, rather than the GDM
loaded at boot time. This bug was causing spurious ResolveNotVersion
results, because servers were reporting that they did not know of the
version we were waiting on - in fact they did, but they were reporting a
snapshot of the GDM from when they booted.

Several enhancements and fixes.

---

config/otpl.go
doc/sous0.1.md
ext/otpl/otpl.go
ext/otpl/otpl_test.go
graph/graph.go
graph/otpldeploy.go
graph/targetmanifest_test.go
lib/manifests.go
lib/manifests_test.go

I figure the best time to add release notes is alongside a PR, so added the following to doc/sous0.1.md ...
- 'sous init -use-otpl-deploy' now supports flavors defined by otpl config directories in the `<cluster>.<flavor>` format. If there is a single flavor defined, behaviour is like before. Otherwise you may supply a -flavor flag to import configurations of a particular flavor.

sous-init -use-otpl respects flavors

---

Makefile

This is super-destructive, so I've hesitated to add something like this to `make clean`. I only use containers for development on my local machine, so this is helpful for me:
1. Kill all running containers
2. rm all stopped containers
3. Delete the generated testregistry_registry image.

Nuke containers from Makefile with clean-containers.

---

Makefile

Removed -r from xargs
'cuz OS X is kinda BSD
The - at the start of a Makefile recipe line means "no worried if this fails"

Tiny change for Makefile compatibility

---

CHANGELOG.md
cli/add_flags.go
cli/cli_test.go
cli/rectify_test.go
cli/sous_rectify.go
config/deploy_filter.go
config/deploy_filter_test.go
graph/sourcecontext_test.go
graph/targetmanifest.go
lib/resolvefilter.go
lib/status_poller_test.go

This is in response to a StatusPoller bug I observed: empty offset or flavors
match all offsets or flavors, even though empty offsets and flavors are
(relatively) common. Maybe the rest of the filterable fields should be treated
the same way (with the defaults being "*" instead of "")? But in the meantime
this was a quick fix for an immediate problem.

Treat Offset "" and Flavor "" as real values.

---

cli/sous_deploy.go
cli/sous_update.go
ext/docker/dockerfile_buildpack.go
graph/graph.go
util/shell/command.go
util/shell/sh.go
util/shell/shell.go

`sous build` now reports the output of docker build (and docker push) on a
Linewise basis.
`sous deploy` emits a couple of lines to explain the ~20 second delay.

A couple of output fixes for sous build and sous deploy

---

.travis.yml
Makefile

Concept here is simple: there's an extra make target called "wip" that creates
and commits a specially named file to the repo. There's a Travis build script
step that fails if that file exists. Since we don't merge failing PRs, there's
no chance we'll accidentally merge an outstanding PR with the WIP tag file.
On the other hand, this means that using a WIP PR to build on Travis becomes
slightly more annoying, since you'll need to inspect the logs to check for
issues. The ideal case would be a separate check that simply looked for the
file and issued a failing check.

Quick stab at mechanizing WIP

---

ext/git/context_test.go
graph/targetmanifest.go
lib/source_context_test.go
test/projects/fail-immediately/Dockerfile

This is a little noisy and corrects a number of issues. See commits for details.
Most important bit is that a bug is fixed where 'sous init' (and every other command that relies on graph.TargetManifest) was not correctly picking up the source location offset. See the self review which follows for details.

Bugfix init offset

---

CHANGELOG.md
ext/singularity/recti-agent.go
ext/singularity/rectifier_test.go
graph/graph.go
integration/integration_test.go

singularity.Deploy() adds Docker labels to SingularityDeploy Metadata
TestDockerMetadataSet()
graph.newDockerRegistry() replaces graph.makeDockerRegistry()
singularity.RectiAgent adds labeller member.

Docker Labels in Singularity Metadata

---

.travis.yml
ext/singularity/deployer.go
ext/singularity/deployer_test.go
ext/singularity/recti-agent.go
ext/singularity/recti-agent_test.go
ext/singularity/rectifier_test.go
integration/integration_test.go
lib/constants.go
lib/deployable.go
lib/dummy_rectification_client.go

I've refactored the Deploy() and PostRequest() functions on the singularity rectificationClient interface, making their method signatures markedly shorter. I removed an unused "Volumes" member from the sous.Deployment struct. I've simplified the DummyRectifcationClient to use lists of Deployables instead of a custom type. ClusterName and Flavor variables have been added to the SIngularityDeploy Metadata field, and constants that determine which key they use are set as constants in the sous package.

ClusterName and Flavor in SingularityDeploy Metadata

---

util/configloader/configloader.go

I want to be aware when Sous is overriding default configuration with values taken from environment variables.
This works, but feels wrong. Alternate approaches welcome.

Log environment variable configuration overrides.

---

ext/docker/image_mapping.go
integration/integration_test.go

Updates the NameCache to record the canonical name of images as being on the
registry host it was configured with as opposed to the registry name returned
in the metadata.
Consequence of this change was that integration tests needed to be updated to
configure the registry.
The returned registry name, if it differs for some reason, is recorded as well,
to minimize unneeded redeploys.

Treat the configured docker registry as canonical

---

.travis.yml
Makefile
staticcheck.ignore

This finds (but I haven't corrected yet) errors like 'err' being
assigned and then ignored.
I'd like to add this to our CI routine, in an effort to end-run certain simple
problems.

Adding `make staticcheck`

---

ext/docker/image_mapping.go
graph/local_config.go
integration/sh_test.go
lib/deployable_chans.go
lib/deployable_chans_test.go
lib/map_state_to_deployments_test.go
lib/resolver.go
lib/resolvestatus.go
lib/resolvestatus_test.go
lib/status_poller.go
lib/status_poller_test.go

Here's the problem: the /status endpoint reports two things: the list of
deployments when the current resolution cycle started, and the resolutions that
have been completed so far. From those two things, the client can figure out
what's up with the deployment it cares about, effectively by answering two
questions: first, is the server working on my deployment? Second, has it
resolved yet?
Because this is polling an ongoing process, we in fact keep two status lists:
the most recent "complete" status, and the current live one. The in progress
list is fresher, but the stable one has a resolution for everything.
Trouble was, we were sharing a single list of deployments between both, which
meant for updates (i.e. not the first successful deployment) the list would
include the new update, and …

Binding the "intended deploytments" to the phase is statuses.

---

ext/singularity/deployer.go
ext/singularity/deployer_test.go

There was a test for "if the deployments are the same, but one is
failed" which specified "do nothing" when in fact, Sous should be
whamming new deploys after failed ones until someone pulls it offa the
jerk.
Test now specifies a change, and the code complies.

Fixed the wrong test; fixed the wrong code

---

CHANGELOG.md
doc/legal_characters.md
ext/singularity/deployer.go
ext/singularity/deployer_test.go
ext/singularity/recti-agent.go
ext/singularity/rectifier_test.go

As restricted by Kafka, Singularity and Mesos. Docker is implied by
Singularity, afaict, but probably worth checking that as well.
Note that there's a disambiguation suffix added (ala deploy ids), but I
think that'll be minimal impact because request IDs get cut off in the web
UI as it is.

Requests limited to only legal characters

---

CHANGELOG.md
dev_support/sous_qa_setup/certificates.go
ext/docker/image_mapping.go
ext/singularity/deployer.go
ext/singularity/deployer_test.go
ext/singularity/deployment_builder.go
ext/singularity/recti-agent.go
ext/singularity/rectifier_test.go
integration/hello-server-labels/nginx.conf
integration/integration_test.go
integration/test-two-updated/.docker-repo
integration/test-two-updated/Dockerfile
integration/test-two-updated/config.js
lib/deployable_chans.go
lib/deployment_diff.go
lib/deployment_diff_test.go
lib/deploystate.go

Singularity stashes its requestID there, and picks it back up to do modify actions.
There's also sundry improved logging, and I've started the idea od
ExecutorMessage for failures - the idea, eventually, is to thread that back
through /status so that `sous deploy` can report details from Singularity - so
that when your task dies on launch, you can at least follow a link to determine
the cause.

Adds an opaque "ExecutorData" field

---

CHANGELOG.md
ext/singularity/deployer.go
integration/integration_test.go

The algorithm used to create a SingularityRequestID needs to be idempotent.

MakeRequestID Digest

---

CHANGELOG.md
Makefile
integration/docker_helpers.go
integration/integration_test.go

It is hoped that this will fix some sporadic test failures by not considering Singularity completely reset until its api returns a zero-length list of active requests.
Extended timeout for integration tests.
Spew in integration tests to pretty-print errors.

Integration Singularity Reset poll loop.

---

lib/http_state_manager.go
util/configloader/configloader.go

The output looked like
"warn: Missing config file, using defaults%!(EXTRA map[string]interface {}=map[path:/home/teamcity/.config/sous/config.yaml])"
because of a mismatch between Printf and no template. Simple update to output more nicely.
Better still would be to give hints about what to do if that's the wrong path
(e.g. the SOUS_CONFIG_FILE env) but this is a general config loader function.

Fixing output for missing config. #trivial

---

CHANGELOG.md
cli/sous_server.go
server/server.go
server/server_test.go

If `sous server` is run with the `-profiling` flag
or with `SOUS_PROFILING=enable`
A /debug/pprof endpoint becomes available,
from which various profiling data can be collected.
c.f. https://golang.org/pkg/net/http/pprof/

Adds profiling endpoints

---

integration/integration_test.go

Removed stray integration test configuration for deprecated Grafana test image.

Remove Startup{} dicta in default integration containers. #TRIVIAL

---

CHANGELOG.md
cli/cli_test.go
cli/sous_server.go

Otherwise it was using the zero value of "" which meant "no offset" or "no flavor" - and ignoring those deployments entirely.

Sous server explicitly sets wildcard for offset and flavor

---

CHANGELOG.md
ext/docker/builder.go
ext/docker/builder_test.go
ext/docker/names.go

Adds a timestamp to the "pinning" label used to keep manifests in the registry.
Also prefixes the label with the character "z" so that they'll all sort together (and last) in lists of labels.

Nicer pinning labels

---

CHANGELOG.md
ext/singularity/deployer.go

singularity: Ensure DeployID < 50 chars.                                
- Previously the tests passed because of an off by one error in         
comparison (checking not greater than rather than strictly less than).
- Singularity spec is strictly less than 50, i.e. max = 49.

singularity: Ensure DeployID < 50 chars.

---

ext/singularity/deployment_builder.go
ext/singularity/deployment_builder_test.go

Otherwise we don't consider changes in the healthcheck to be deployable

Pulling healthcheck data from Singularity #trivial

---

CHANGELOG.md
ext/singularity/deployer.go
ext/singularity/deployer_test.go

Failing test for ComputeDeployID
- When the version string is exactly 17 chars long, we get a DeployID
50 chars long, which is too long.

singularity: Fix regression with Singularity DeployIDs len > 49

---

CHANGELOG.md
ext/singularity/deployer.go
ext/singularity/deployer_test.go

Includes #400 
Adds table-driven tests that document edge cases in Singularity deployId generation, to help us avoid introducing regressions in future.

Singularity deployId tests

---

CHANGELOG.md
ext/singularity/deployer.go
ext/singularity/deployer_test.go

Includes #401 
Changes constant `maxRequestIDLen` to equal `99`, matching the maximum allowed request ID length. Also makes a tiny refactoring of singularity deployId length comparison, for consistency.

Max request ID length #trivial

---

ext/singularity/deployer_test.go
ext/singularity/deployment_builder.go
ext/singularity/recti-agent.go

Note, this also starts a pattern of tests related to roundtripping
a deployment
into a request/deploy pair
to JSON
back into request/deploy
into a deployment
and comparing to the original.
Failures in this test are cases where we'll get into a redeploy cycle.
New cycles should be put into this pattern, so that we can ward off regressions.

Fixing spurious diff related to healthcheck timeout

---

CHANGELOG.md
Makefile

I frequently want to switch between running a personal dev build of Sous and the latest official release from Homebrew. This PR adds two complementary make targets: `install-dev` and `install-brew`. They are complementary because running either of these commands will remove the version of sous installed by the other.
- `install-dev` adds a timestamp to the build as well, so you can be sure you're using a fresh one.
- `install-brew` and `install-dev` are both too rough for non-sous-developers to use, as they just indiscriminately delete `$(which sous)`.
- You should run `hash -r` manually after running either of these to make sure you're running the version you expect.
You can see it spits out errors in normal operation. This could be refined, but I'm happy with it for now as it's only for …

Install dev

---

CHANGELOG.md
ext/otpl/otpl_test.go
integration/integration_test.go
lib/deploy_config.go
lib/deployment.go
lib/deployment_test.go
util/allfields/allfields.go
util/allfields/confirmtree.go
util/allfields/conftree.go
util/allfields/tester/main.go

Adds: static analysis of Go code,
to extract a "confirmation tree" based on a struct and its struct members,
and then walking the AST of a method definition to check that
all the members are "touched" by the function.
A couple of shortcomings of the analysis:
loops in struct definitions
(trivial example: a linked list)
will never complete.
Function return values aren't considered,
so using a function to extract a sub-struct
and then operating on the result
won't be detected.
It may be that
functions that use confirmation tree nodes
as arguments (as opposed to as the method receiver)
won't be considered.
(To be clear, methods of the confirmation nodes are checked.)
Finally,
non-struct composites
(maps and slices)
are considered "leaves"
of the confirmation tree -
we don't confirm that
e.g. …

Deployment.Diff static analysis checking.

---

CHANGELOG.md
ext/storage/git_state_manager.go
ext/storage/git_state_manager_test.go

Test changes were surprising in the extent. Turns out that the old tests didn't
seem to actually be testing the git part of things.

GitStateManager now returns an error if any push would include more than one file.

---

CHANGELOG.md
ext/singularity/actual_deployment_set.go
ext/singularity/deployer.go
ext/singularity/deployer_test.go
ext/singularity/deployment_builder.go

- Also remove an odd looking recover() from reading
SingularityRequestParent. Also remove named output
that was stuttering, and simplify flow.
Previously the stack trace was being printed, but not near where the error was handled. Hopefully printing it where we handle the error will make the logs easier to read.

singularity: Add stack trace to recovered errors.

---

CHANGELOG.md
lib/build_config.go
lib/source_context.go

Addresses an issue where 'sous build' fails when tag has a non-numeric prefix. Related to #413

fix: Semver tag with prefix validation.

---

CHANGELOG.md
ext/storage/git_state_manager.go
ext/storage/git_state_manager_test.go
ext/storage/preparetestgitrepo.go
graph/testsupport.go
lib/state.go
server/graph.go
server/handle_gdm.go
server/handle_gdm_test.go
server/server_test.go
test/http_state_manager_test.go
util/restful/router.go

The state gets an etag from the GitStateManager
(the revision of the current head).
The restul.Server will reject PUTs unless they
If-Match the current git-rev Etag.
The Etag gets set on the written state,
which the GSM checks against the head revision.
The upshot should be that it is impossible now to make an update
to the GDM unless
you are basing that update on the current revision.

Implements locking Git state via Etags

---

cli/sous_plumbing_normalizegdm.go

This just reads the SOUS_STATE_LOCATION into memory and then writes it back.
Because storing is a stable operation, but the format is flexible enough to
represent the same configuration many ways, it's easy to produce an intended
configuration in a way that will be stored in a different textual form. The
result is that spurious differences cause a conflict in the GitStateManager and
prevent deploys.
It's possible that running `sous plumbing normalizegdm` after any manual
changes to the Git backed GDM will alleviate this problem entirely.

Adding 'plumbing normalizegdm'

---

cli/deploy_filter_flags.go
cli/sous_manifest_test.go

Very simple fix makes `sous manifest {get,set}` honor the -flavor flag.

Adding a -flavor flag so that existing functionality will work.

---

CHANGELOG.md
cli/cli.go
cli/cli_test.go
cli/sous_deploy.go
ext/storage/git_state_manager.go
graph/graph.go
graph/server_injection_test.go
util/cmdr/cli.go

There was a problem with how DI contexts were being passed around: the command object responsible for `sous server` registered providers with its DI, but the actual server component didn't get that DI - it got one from further up the chain of contexts, which meant that important machinery wasn't available - so the server would blow up when certain requests were made of it.
Fixing this involved pulling a fair amount of the plumbing out and packing it back in.

Fixes a DI context issue between CLI and server injection.

---

CHANGELOG.md
util/restful/httpclient_test.go
util/restful/putbackjson.go

Null fields were being put into the proposed document, then removed because
they weren't being marked as found (by deletion from the base map.)

Fixes `manifest set` JSON putback.

---

CHANGELOG.md
ext/docker/splitcontainer_runnablebuilder.go

Because of how Docker handles `docker cp` paths,
and how Go's filepath handles joining,
there's an oddity about how run containers were being build.
This fixes the extra path component that was being added.

Fixes a bug in the splitbuild

---

CHANGELOG.md
graph/otpldeploy.go

sous init -flavor EU -ignore-otpl-deploy
panic: uninitialised Manifests (you should use NewManifests)
goroutine 99 [running]:
panic(0x47bcf00, 0xc4205f0040)
/usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/opentable/sous/lib.Manifests.read(0x0, 0x0, 0xc4205db478)
/ext-go/1/src/github.com/opentable/sous/lib/manifests_generated.go:36 +0xde
github.com/opentable/sous/lib.Manifests.Len(0x0, 0x0, 0x4030170)
/ext-go/1/src/github.com/opentable/sous/lib/manifests_generated.go:211 +0x68
github.com/opentable/sous/graph.newUserSelectedOTPLDeploySpecs(0x0, 0x0, 0xc420530ab0, 0x28, 0x0, 0x0, 0x7fff5fbff4ca, 0x2, 0xc4200ec8e8, 0xc42047f880, ...)
/ext-go/1/src/github.com/opentable/sous/graph/otpldeploy.go:30 +0xba
reflect.Value.call(0x4800700, 0x4957388, 0x13, 0x48b319b, 0x4, 0xc420516000, 0x4, …

Fix panic caused when using ignore-otpl-deploy

---

CHANGELOG.md
cli/sous.go
cli/sous_server.go
util/logging/config.go

Everything should be using the LogSink interface, not LogSet
n.b. that there are many uses of the global logging.Log LogSet - which
means that e.g. the logwrappers can't be removed yet - the correct
behavior, where possible, should be to replace those uses with injected
LogSinks.
TECHOPS-3149 TECHOPS-3152

Commands were using logging.LogSet directly TECHOPS-3149 TECHOPS-3152

---

CHANGELOG.md
ext/docker/image_mapping.go
ext/docker/image_mapping_test.go
graph/graph.go
graph/graph_test.go
integration/deployment_builder_test.go
integration/integration_test.go

* Wraps DDL modifications in a Once
* Reports on errors from the DDL change
* "scoops" out NameCaches instead of reusing the constructor

Fixes DB DDL related race condition

---

CHANGELOG.md
cli/cli.go
cli/cli_test.go
cli/sous.go

Previous fix for the singleton NameCacheb
knowingly broke -d and -v.
This approach gets us both options.

Restores debugging flags

---

CHANGELOG.md
util/logging/applicationid.go
util/logging/applicationid_test.go
util/logging/logging.go
util/logging/messages.go
util/logging/messages/messages_test.go
util/logging/testsupport.go

Adds metrics scope (sous.<env>.<region>)
Pulls environment variables correctly into reports, instead of "unknown"

Reporting orthodoxy

---

vendor/github.com/samsalisbury/psyringe/ctor.go
vendor/vendor.json

Also prints an HTTP error message in some cases. ~Note that because injection order is nondeterministic, when the server is down you will see one of 3 error messages when server unavailable.~
**EDIT:** Fixed a bug in psyringe that was allowing constructors to be called despite one of their dependencies failing. This has the result that we now get stable error messages including the HTTP status code returned from the server. See https://github.com/samsalisbury/psyringe/commit/afa419dfe20cdfb9c1ed69eb5ea6e400f32954ec

Eliminate segfault on server HTTP error

---

CHANGELOG.md
ext/singularity/deployment_builder.go
lib/startup.go
lib/startup_test.go

* Diff method of Startup now diffs value of SkipCheck.
* Singularity DTO round-trips nil `SingularityDeployment.Healthcheck` as `Startup.SkipCheck = true`.

Startup.SkipCheck changes now results in re-deployment

---

CHANGELOG.md
cli/sous_manifest_get.go
cli/sous_manifest_set.go
graph/sourcecontext_test.go
graph/targetmanifest.go
graph/targetmanifest_test.go

Ideally this needs an integration test but not got that far yet. All existing tests pass, and I have manually verified it so opening PR for discussion.
Most of the commits here just add or tidy up unit tests. The crux of this change is https://github.com/opentable/sous/commit/21bf57ec2edf5ce73474a228a24db79ccef53b2c

Autodetect offset for deploy, manifest get & set 

---

CHANGELOG.md
cli/sous_init.go

- This lets us see what manifest would be created without actually
creating it. It also bypasses checking if it already exists.

cli: sous init -dryrun flag

---

.travis.yml
CHANGELOG.md
Dangerfile
Gemfile.lock
bin/release-update
ext/docker/cachemessages.go
graph/graph.go
integration/integration_test.go
lib/auto_resolver_test.go
lib/deployable_chans.go
lib/deployable_chans_test.go
lib/deployment.go
lib/deployment_diff.go
lib/fixtures_test.go
lib/loggingprocessor.go
lib/nameresolver.go
lib/pipeline.go
lib/resolver.go
lib/resolver_test.go
lib/resolvestatus.go
util/logging/graphiteconfigmessage.go
util/logging/kafkaconfigurationmessage.go
util/logging/testsupport.go

Includes a shift in architecture around how DeployableChans work:
The differs produce DeployableChans, on which Pipeline() gets called to add
processors. ResolveNames is now a specialization of Pipeline().
Logging is handled by a pipeline processor.
Also included: the logging.AssertMessageFormat helper emits propsed OTLs to $TMPDIR.
They're not ready for immediate inclusion, but they sure save a lot of work.

Log entries for deployment diffs

---

CHANGELOG.md
lib/loggingprocessor.go
lib/loggingprocessor_test.go
util/logging/messages.go
util/logging/panic_test.go

There's a test now for the diff messages, such that they omit fields
rather than drill down into nil fields (and thereby panic.)
Futhermore, there's a rescue in Deliver - if there's a panic in the
course of delivering a message, we log a (well tested and simple)
silentMessageErr - which will report the type of the "silent message":
loggingPanicFakeMessage, which is a signal that a log message panicked.
We'll get a log entry to mark the panic, but Sous won't crash because
formatting code related to producing a log message panicked.

Defensive programming for panics SOUS-728

---

CHANGELOG.md
lib/dummy_rectification_client.go
lib/resolvestate.go
lib/status_poller.go
lib/status_poller_test.go
util/logging/applicationid.go
util/logging/applicationid_test.go

The crucial part of this PR is the rather verbose `computeStatus` function. Because we have different rules to handle `ResolveComplete` vs `ResolveFailed` simple comparison with `ResolveTERMINALS` isn't very helpful for this method. The test `TestStatusPoller_updateState` reveals the new spec for computing this state.
Other changes include making `ResolveFailed` greater than `ResolveComplete` since when computing `maxStatus` we want failed states to take precedence over successful ones (although this may not now be important with the latest implementation of `computeStatus`.
I was using the race detector to check for anything fishy that might be affecting these tests, as a result this PR includes a couple of fixes for race conditions which were probably not relevant to the eventual …

Poll full resolution

---

CHANGELOG.md
cli/cli.go
cli/sous.go
cli/sous_manifest.go
cli/sous_manifest_get.go
cli/sous_manifest_set.go
cli/sous_metadata_get.go
cli/sous_metadata_set.go
graph/graph.go
util/cmdr/cli.go
util/cmdr/help.go
vendor/github.com/samsalisbury/psyringe/README.md
vendor/github.com/samsalisbury/psyringe/psyringe.go
vendor/vendor.json

The issue was that NameCache was being injected unconditionally, and it requires a valid config, so validation was running and causing sous to barf with invalid config on all commands (including 'sous config' which should tolerate invalid config so it can be fixed).
The unconditional injection of the name cache has been removed, and changes made to both `cli` and `cmdr` packages. `cmdr` no longer forwards flags from commands higher up the tree, and now only calls the `Parsed` hook once, for the final command in the invocation. This means that where we relied on things being added to the graph by 'RegisterOn' methods higher in the tree, we now need to add them directly to the leaf command. Flags from the `Sous` command which were passed down are now implemented as global flags using a …

'sous config' allows fixing broken config

---

CHANGELOG.md
cli/actions/messages.go
cli/sous_deploy.go
lib/messages.go
lib/messages_test.go
lib/resolvestate.go
lib/status_poller.go

The Update action and the Status pollers now emit console messages,
which means that `sous deploy` is much more descriptive of what it's doing.
Note that I also found and fixed a bug where status was checked in a very tight loop
and was issuing far too many update messages on kafka.

Output from status polling SOUS-259

---

CHANGELOG.md
doc/developer_adding_manifest_fields.md
ext/singularity/deployer.go
ext/singularity/deployer_test.go
ext/singularity/deployment_builder.go
ext/singularity/recti-agent.go
ext/storage/testdata/in/manifests/github.com/opentable/sous.yaml
ext/storage/testdata/in/manifests/github.com/user/project.yaml
lib/deploy_config.go
lib/deploy_spec.go
lib/deployment.go
lib/map_state_to_deployments.go
lib/map_state_to_deployments_test.go

Manifests now get a Schedule field for cron-style scheduled tasks.
Note that because of how serialization works, this field will be added to all manifests -
watch for "more than one file"  errors during deploy.
(The GDM may need to be renormalized.)
Also appearing: a lightly annotated diff-log of the changes required,
and the change/test process I go through to add a field.
Should make adding other fields more reasonable.

Adding Schedule field #SOUS-8 #SOUS-753

---

cli/cli.go
cli/sous.go
cli/sous_build.go
cli/sous_context.go
cli/sous_deploy.go
cli/sous_init.go
cli/sous_manifest_get.go
cli/sous_manifest_set.go
cli/sous_metadata_get.go
cli/sous_metadata_set.go
cli/sous_plumbing_status.go
cli/sous_rectify.go
cli/sous_server.go
cli/sous_update.go
graph/testsupport.go
vendor/github.com/samsalisbury/psyringe/experiment/optionalfieldshandler.go
vendor/github.com/samsalisbury/psyringe/hooks.go
vendor/github.com/samsalisbury/psyringe/psyringe.go
vendor/github.com/samsalisbury/psyringe/testpsyringe.go
vendor/vendor.json

Injection is now mandatory for all struct fields injected into in the CLI.
You can add `inject:"optional"` tag to any field to disable this.
Trivial because this is dev-facing change only. We should run the CLI tests if poss to verify this doesn't break anything. Integration + unit tests passing, and casual use of this build verifies it's at least mostly working still.

Optional injection #trivial

---

CHANGELOG.md
Makefile
cli/cli.go
cli/cli_test.go
cli/tests/terminal.go
config/config.go
graph/graph.go
graph/graph_test.go
graph/local_config.go
graph/testsupport.go
lib/manifestkind.go
main.go
test/http_state_manager_test.go
util/configloader/configloader.go
util/logging/config.go
util/logging/logging.go
util/logging/messages.go

- Before, we always had a logSet configured to use os.Stderr
- Now we use the graph, including config to create a log set, which therefore respects config: `Logging.Basic.DisableConsole`

Logging: CLI respects Logging.Basic.Level SOUS-756

---

CHANGELOG.md
cli/cli.go
cli/global_flags.go
cli/sous.go
cli/tests/sous_test.go
cli/tests/terminal.go
config/verbosity.go
graph/actions_test.go
graph/graph.go
graph/graph_test.go
graph/local_config.go
graph/testsupport.go
main.go
test/http_state_manager_test.go
test/server_integration_test.go
test/server_test.go
util/configloader/configloader.go
vendor/github.com/samsalisbury/psyringe/testpsyringe.go
vendor/vendor.json

CLI flags take precedence over config file options, so the flags should now work as expected.
*Update* now safe to merge.

flags: -s, -q, -v, -d now set verbosity correctly

---

CHANGELOG.md
cli/actions/server.go
cli/actions/server_test.go
cli/cli_test.go
cli/sous_query.go
cli/sous_server.go
graph/actions.go

The profiling boolean was getting injected by value before checking the environment.
Fixed that, and also extracted Server as an Action while I was there.
I've tested the profiling configuration locally. If we can get this into production ASAP,
we can start experimenting with the profiling output to see if it tells us anything
about the rectification cycle.

Enable profiling environment variable.

---

doc/install.md

- We used to tag with v1.2.3 now we use 1.2.3 bare.

doc: install: fix download URL format

---

Makefile
database/changelog.xml
dev_support/postgres/postgresql.conf
shell.nix

This PR adds make targets that allow for a development database to be set up quickly.
It currently requires that you have Postgres 10 and Liquibase installed (with
the 42.1 version of the Postgres JDBC driver). I'm afraid this requirement will
be onerous for other devs, so I want to check that assumption.
Once you have the required software installed, these commands should work:
`make postgres-start`
This is not only start development Postgres server,
it will also build the requisite data directory,
and use the Liquibase changelog to update its schema.
`make postgres-connect`
Connects psql to the dev database. Just a convenience -
it means you don't have to know or remember the connection parameters.
`make postgres-stop`
Shuts down the development server.

Make targets and liquibase scripts

---

CHANGELOG.md
ext/storage/postgresstatemanager_test.go
ext/storage/postgresstatemanager_write.go

Things like table and column names are still being interpolated, since those
are all controlled by the program and known at compile/testing time.
Tests exercise ~30 placeholder parameters. I guess we'll see if there's a hard
upper limit. I wasn't able to find an documentation to the effect.

Using placeholders for data-sourced values

---

CHANGELOG.md
util/logging/config.go
util/logging/config_test.go

If you don't specify brokers for kafka, the validation never actually catches error.
https://stackoverflow.com/questions/35866221/why-does-an-empty-array-returned-from-strings-split-have-a-length-of-1-in-golang

Fix validate check

---

CHANGELOG.md
lib/r11n_queue.go
lib/r11n_queue_test.go

As per title, this fixes a data race picked up by the race detector (between `.init` and `.Start`) and addresses an issue where we would occasionally deadlock due to interaction between `next` and `pop` methods. The `pop` method was not in use and has been removed.

Fix r11n queue race

---

CHANGELOG.md
config/config.go
ext/storage/duplexstatemanager.go
ext/storage/duplexstatemanager_test.go
ext/storage/logonlystatemanager.go
ext/storage/logonlystatemanager_test.go
ext/storage/messages.go
ext/storage/postgresstatemanager.go
ext/storage/postgresstatemanager_read.go
ext/storage/postgresstatemanager_test.go
ext/storage/postgresstatemanager_write.go
graph/graph.go
graph/graph_test.go
lib/status_poller_test.go
util/configloader/configloader.go
util/logging/errors.go
util/logging/errors_test.go

The goal here is to keep the two states in sync until we're ready to switch over.
Note that if there's a problem connecting to the DB,
or saving state to it, there's only a log entry -
the designed intent here is that the secondary store
not influence the operation of Sous.

Duplex state storage, copies state out to Postgres DB

---

Dangerfile

If a change to a code file only adds or removes:
* a comment
* a blank line
then ignore that file for purposes of PR review.

Danger: ignore insignificant changes

---

CHANGELOG.md
ext/singularity/actual_deployment_set.go
ext/singularity/deployer.go
ext/singularity/deployer_test.go
ext/singularity/deployment_builder.go
ext/singularity/deployment_builder_test.go
graph/graph.go
integration/deployment_builder_test.go
integration/docker_helpers.go
integration/integration_test.go
lib/resolver.go
lib/resolvestatus.go
lib/resolvestatus_test.go

Slight simplification to ResolveRecorder interface (yagni'd performGauranteedPhase)
Transformed table tests to t.Run with helpers.
Sam and I agreed that there's no outside-facing change to this, and it shouldn't have a CL entry.

Corrects itermittant failure in TestResolveRecorder #trivial

---

CHANGELOG.md
graph/graph.go

The logging infra allows for "child" loggers, which scopes log entries and metrics.
The graph, as the top-level place where loggers get injected, should be
the first place those scoped loggers get used.

Scoping loggers as much as possible

---

CHANGELOG.md
ext/singularity/deployermessage.go
util/logging/messages.go
util/logging/panic_test.go

Not saying we should do this, but this but since we cover panics in logging, there are definite cases where even our unit tests won't necessarily be correct, though it does help if call AssertMessageFields....

Panic if run by go-test

---

graph/graph.go
graph/graph_test.go
graph/server.go
integration/integration_test.go
lib/auto_resolver_test.go
lib/resolver.go
server/handle_alldeployqueues.go
server/handle_alldeployqueues_test.go
server/handle_deployqueue.go
server/handle_deployqueue_test.go
server/handle_r11n.go
server/handle_r11n_test.go
server/server.go

- Also removes the global queue set that was always a smell.
**EDIT** marked this as trivial since it simply makes the current changelog entry about this true.

#trivial server/lib/graph: inject R11nQueueSet

---

server/handle_deployqueue.go
server/handle_deployqueue_test.go
server/handle_manifest.go
server/handle_r11n.go
server/handle_r11n_test.go
server/queries.go

We decided it would be easier for external API consumers to be able to specify the parts of a DeploymentID separately as query values rather than as a single concatenated string, this change effects that idea.
EDIT: Marked #trivial because the unreleased changelog already lists the addition of these endpoints.

#trivial Deploy queue endpoints use separate query values.

---

bin/jira-fixversion

bin/jira-fixversion works to tag all closed issues as being fixed with the most
recent tagged Sous version.
It relies on `git config` commands to determine Jira configuration -
the recommendation is to configure those such that e.g. they won't be pushed to a dotfiles repo.
If the current version isn't yet recorded in Jira, it will be created unreleased,
so that we can review closed tickets as a team before considering them released.

Adding fixversion script

---

ext/singularity/deployment_builder.go

- UnmarshalFieldError has been unused since early 2013:
https://github.com/golang/go/commit/6e3f3af4e0f4293f868aa71c4271cab6344d5797#diff-3be5c7b44b3117ade8424ec490983cb6R109
- In go 1.10 it is marked deprecated using GoDoc comment:
https://github.com/golang/go/commit/a3e013b0824ba53168b5d91abdb6ce191510a89d#diff-e79d4db81e8544657cb631be813f89b4R249
- This caused make staticcheck to fail with go 1.10

#trivial singularity: remove reference to deprecated type

---

ext/storage/preparetestgitrepo.go
test/server_integration_test.go

- I get intermittent failures where test setup fails to
remove testdata directories.
- I put these changes in to try & debug the problem, ~and
it appears to have stopped happening, not sure if this
fixed it or if after 5+ test runs the issue cleared by
itself.~
- Worth keeping these changes in case it happens again.
**Update:** these test failures continued to happen frequently, I've added a further commit that puts generated test data in a separate temp dir per test so they don't interfere with each other. Also added cleanup to save filling up disks. This looks to have solved the issue on my machine, but I can see other places we could apply this pattern. Has anyone else seen intermittent failures like those below?
```
--- FAIL: TestOverallRouter (0.05s)
preparetestgitrepo.go:57: "git …
```

#trivial storage/test: make repo paths abs; add t.Helper()

---

Makefile

https://github.com/2tvenom/go-test-teamcity
Will use this to create A TC project that runs these and reports in standard TC reporters
Example:
`##teamcity[testFinished timestamp='2018-03-05T18:37:24.335' name='TestCanMakeAnAgent']
##teamcity[testStarted timestamp='2018-03-05T18:37:24.335' name='TestUntilReady']
##teamcity[testFinished timestamp='2018-03-05T18:37:24.335' name='TestUntilReady']
PASS
ok      github.com/opentable/sous/util/test_with_docker 3.342s
##teamcity[testStarted timestamp='2018-03-05T18:37:24.335' name='TestValidate_NestedStructs']
##teamcity[testFinished timestamp='2018-03-05T18:37:24.335' name='TestValidate_NestedStructs']
##teamcity[testStarted timestamp='2018-03-05T18:37:24.335' name='TestValidate_Interface_InvalidKey']
##teamcity[testFinished …

add teamcity formatting for unit tests

---

cli/sous_newdeploy.go
graph/graph.go
lib/rectification.go
server/handle_single_deployment.go
server/handle_single_deployment_test.go

'sous newdeploy' now selects the appropriate server to issue PUT /single-deployment to. Previously it always tried to put the the server in user's config which is not always appropriate.
Also fixed: PUT /single-deployment returns a Location header pointing to a rectification which can be watched for completion. However, the URL in Location header was missing DeploymentID query params, so the R11n could never be found. This PR adds the remaining query params so this relative URL is complete.

Hit specific server + return all query params in Location from PUT /single-deployment #trivial

---

lib/rectification.go

- The close(done) was panicking occasionally even though I cannot
find any other reference to that channel.
- Could be a bug in sync.Once or something weirder (is the once being
copied in a way that breaks the pattern somewhere?).

lib: bandage close of closed channel #trivial

---

CHANGELOG.md
cli/cli.go
graph/graph.go
util/logging/messages/generalmsg.go
util/logging/messages/generalmsg_test.go

It's been a longstanding bug that when e.g. `sous query gdm` or
`sous manifest get -repo ...` was run outside of a git repo, it would crash
with a git error. This PR fixes that, since those use cases are pretty useful.
Also cleans up some logging & console interactions.

Fixes sous-without-workspace issue.

---

CHANGELOG.md
cli/actions/server.go
cli/sous_server.go
graph/actions.go
lib/resolver.go

Adds a flag to sous server to disable the autoresolver.
This is only intended to be used for local debugging efforts,
so it has not been made a configuration option.
There's also a couple of logging cleanups and linter satisfaction changes.

`sous server -autoresolver=false`

---

cli/sous_newdeploy.go
graph/server.go
integration/integration_test.go
lib/auto_resolver_test.go
lib/deployment_manager.go
lib/nameresolver.go
lib/r11n_queue.go
lib/r11n_queue_set.go
lib/rectification.go
lib/rectification_test.go
lib/resolver.go
lib/state_fixture.go
lib/state_manager.go
server/data.go
server/handle_gdm.go
server/handle_single_deployment.go
server/handle_single_deployment_test.go
test/server_integration_test.go
util/logging/messages/generalmsg_test.go
util/restful/client.go

Finishes off #636 and reverts SingleDeploymentBody to use DeploySpec not full Deployment (since full Deployment is a denormalised blob and very unwieldy for API consumers; also contains many fields that cannot be modified).

Build artifact needed

---

CHANGELOG.md
cli/actions/server.go
ext/storage/disk_state_manager.go
ext/storage/disk_state_manager_test.go
ext/storage/messages.go
ext/storage/postgresstatemanager_read.go
ext/storage/postgresstatemanager_write.go
ext/storage/testdata/in/manifests/github.com/user/project.yaml

Cause was that deployments with 0-length owners lists weren't being selected.

Fixes deployment leak in DB

---

util/logging/kafkasink.go

- Longer than kafka allows but less than 5000 chars was causing panic.
- Now we just log up to the first 5000 chars of messages that are too
long.

logging: fix panic when kafka messages too long

---

CHANGELOG.md
server/data.go
server/handle_single_deployment.go
server/handle_single_deployment_test.go

- No longer validates the partial deploy spec from the request
since we expect that to be incomplete information.
- Validation is still done after round-tripping the new DeploySpec
to the GDM so that default values are added.

server: /single-deployment deployspec validation

---

CHANGELOG.md
ext/singularity/actual_deployment_set.go
ext/singularity/actual_deployment_set_test.go
ext/singularity/deployer.go
ext/singularity/deployerconfig.go
ext/singularity/deployment_builder_test.go
ext/singularity/requeststate.go
ext/singularity/requeststate_test.go
ext/singularity/singclient.go
graph/server.go
integration/deployment_builder_test.go
integration/integration_test.go
integration/test-one/Dockerfile
integration/test-three/Dockerfile
integration/test-two/Dockerfile
lib/deployer.go
lib/deploystate.go
lib/r11n_queue.go
lib/rectification.go
lib/rectification_test.go
lib/registry.go
lib/resolvestatus.go
server/handle_r11n_test.go
vendor/github.com/samsalisbury/psyringe/psyringe.go
vendor/vendor.json

This'll mean that the time between Rectification.Begin() is called and Wait() will
return will be much longer, but once it completes, the service should either be
live in Singularity or failed.
Room for future work: synchronzing the Rectification.Resolution and reporting
it on the endpoint to give "live-er" responses to users.

Rectifier polls singularity for deploy to complete.

---

CHANGELOG.md
integration/integration_test.go
lib/resolve_errors.go

This should fix one of the causes of slow integration tests

Exit early from resolving Singularity in integration tests for failures

---

graph/graph.go
graph/graph_test.go
graph/local_config.go
graph/local_config_test.go
lib/build_config.go
lib/build_config_test.go
lib/build_manager.go
lib/build_manager_test.go
lib/deploy_config.go
util/configloader/configloader.go
util/configloader/configloader_test.go

Beginning work on removing global logger...
Note I've removed some logs in `.Equal` methods, they need to be reinstated at call sites. It does not seem reasonable to inject a logger into these DTOs, but callers of `.Equal` should have more context so once reinstated the logs should be a lot more useful.\
**UPDATE** it has been proposed that we might not need the removed logging lines at all, I agree that these are trace-level logs that probably aren't generally useful, so I'm happy to just leave them removed.

#trivial Remove global logger from 3 types

---

shell.nix
util/logging/fieldspecializations.go
util/logging/fieldspecializations_test.go

Treat memory as a long for logging purposes

---

integration/test-registry/docker-compose.yml
integration/test-registry/singularityservice/Dockerfile

- Mesos and zookeeper now match what we're running in all envs.
- Singularity matches latest version in QA.

test-registry: zk 3.4 mesos 1.3.1 sing 0.19.2 #trivial

---

.travis.yml
Makefile

Because coverage reporting cost almost nothing in terms of time,
(possibly because -race dominates?) added coverage flags to main unit tests.

Restoring codecov result reporting to Travis SOUS-960 #trivial

---

lib/state_fixture.go
test/smoke/newdeploy_test.go
test/smoke/testbunchofsousservers_test.go
test/smoke/testclient_test.go
test/smoke/testfixture_test.go
test/smoke/testpids_test.go
test/smoke/testsingularity_utils_test.go
test/smoke/testutils_test.go

Covers 'deploy' as well as 'newdeploy' and covers a failing task. There have been reports of misreporting deployment success, this is an attempt to reproduce the issue. So far it does not reproduce the issue.
**UPDATE** doubling the number of tests (by running on deploy as well as newdeploy) made these tests take about 15 mins on my machine; too long. By making them run in parallel, they now complete in 2m20s on my machine.

Smoke test cover 'deploy' #trivial

---

CHANGELOG.md
cli/actions/deploy.go
util/restful/client.go

` jc  jc-linux  ~  go  …  github.com  opentable  ot-go-static  master  255  $ 
$ sous deploy -flavor doesnotcomputer -cluster dev-ci-sf
Using server http://127.0.0.1:8888
Failed to retrieve current deployment:
Please check your repo, flavor, and offset.   Items are case sensative.  Use the following command to verify values sous expects.
sous query gdm
Error returned: Retrieve ./single-deployment params: map[cluster:dev-ci-sf offset: flavor:doesnotcomputer force:false repo:github.com/opentable/ot-go-static]: 404 Not Found: No manifest with ID "github.com/opentable/ot-go-static~doesnotcomputer"
([78 111 32 109 97 110 105 102 101 115 116 32 119 105 116 104 32 73 68 32 34 103 105 116 104 117 98 46 99 111 109 47 111 112 101 110 116 97 98 108 101 47 111 116 45 103 111 45 115 116 97 …

more info on can't find manifest

---

ext/singularity/actual_deployment_set.go
ext/singularity/deployment_builder.go

removed unused variable to function call isMallformed, broke out ignorable to debug level message.

#trivial update so not logging if don't care about singularity

---

ext/docker/builder.go
lib/buildpack.go

The docker label (used to collect information about the image)
now uses the git commit id (i.e. the revision SHA) again.

Switching back to using revid in labels #trivial

---

Makefile

- Excluding .git and .smoketest speeds up makefile initialisation.
- Excluding attempted .deb build when not on Linux means we can run `make release` on Darwin.

Makefile: exclude .git/.smoketest+no deb on Darwin

---

CHANGELOG.md
config/config.go
graph/actions_test.go
graph/graph.go

Adds a configuration option `DatabasePrimary` (overridden with
`SOUS_DATABASE_IS_PRIMARY`) which selects which of the datastores to "prefer."
The other is merely updated, but not considered for the current state. This is
the current behavior, with Git as primary and Postgres as secondary.
When the DatabasePrimary config is set, Postgres is considered the sole source
of truth.  This should **not** yet be used in deployment - running smoke tests
with this enabled makes it clear that the "empty" database isn't complete
enough (the tests fail).
It's possible that the has-been-run-as-secondary database is ready to be used
as primary, but I'd like to have a from-scratch solution ready before we try to
roll that out.  We could try it, I suppose in dev and see what happens...
Regardless, this …

SOUS-919: Primary store toggle

---

CHANGELOG.md
cli/sous_manifest_edit.go
util/tempfile/tempfile.go

Manifest edit was not working for me, this resolves that issue, see commit comments.
Bonus feature: to get text editors to use YAML formatting and highlighting, this adds a .yaml extension to the temp file.

Manifest edit fix

---

CHANGELOG.md
cli/sous_init.go
cli/tests/sous_test.go

The change to the error message should be uncontroversial. However, this change explicitly breaks any attempt to `sous init -kind on-demand`. AFAIK (looking at current usage at OpenTable) we are not supporting on-demand jobs, so best to let people know as early as possible.

Init flags messages/fail for -kind on-demand

---

.gitignore
Makefile
cli/actions/server.go

`make local-server` allows running a sous server locally that emulates a real deployed cluster-specific sous server. This is intended for bootstrapping purposes only and comes with an embarrassment of warnings about why it's possibly a bad idea to use.

Localserver #trivial

---

CHANGELOG.md
util/restful/client.go

- Now we quit early if the content-type is not JSON
- Also a change to processing in the case we are in an error state,
do not continue with enriching state.
- Error message is now a simple string with the 'GET \<url\>: \<error\>' for clarity.

restful: Client.Retrieve check content type

---

cli/sous_init.go
ext/otpl/otpl.go
lib/internalsupportfortest.go
test/smoke/otpl_test.go
test/smoke/smoke_test.go
test/smoke/testclient_test.go
test/smoke/testfixture_test.go
test/smoke/testmanifesttransforms_test.go
test/smoke/testutils_test.go

Numerous small fixes to output made in preparation for deeper testing.
- Test macros introduced that perform initialisation and shorten test cases.
- setupProject now accepts a `filemap.FileMap` to allow more complex projects than single dockerfiles to be tested (this is necessary for `-offset` flag tests and otpl-deploy integration tests.
- Test output is now more terse so successful tests take up a lot less vertical space reducing noise.

Smoke test preparations for deeper testing #trivial

---

.travis.yml
Makefile
test/smoke/build_splitcontainer_test.go
test/smoke/configmatrix_test.go
test/smoke/otpl_test.go
test/smoke/paralleltestfixture_test.go
test/smoke/smoke_test.go
test/smoke/testclient_test.go
test/smoke/testfixture_test.go
test/smoke/testmain_test.go
test/smoke/testpids_test.go
test/smoke/testprojects_test.go
util/filemap/filemap.go

Adds builder type as a dimension to all other smoke tests.
This doubles the number of tests, and thus requires a lot of ram (for safety 4G) to run the tests. Full test run takes about 8 minutes locally.
Opening a PR to see if Travis can handle this or not. Most likely we need to do 2 things:
1) Run smoke tests selectively on each PR, run full suite nightly, and
2) Have tests clean up as they go (killing Singularity requests) to reduce memory footprint required.
If this all passes happily in Travis, and on core committer's machines, should be safe to merge, otherwise I'll address the above issues first.

Splitcontainer smoke tests #trivial

---

CHANGELOG.md
graph/actions.go

- Previously any value including empty string was considered 'on' which
was hard to use in scripts.
- Now it must be exactly uppercase YES in order to be considered on.

graph: SOUS_USE_SOUS_SEVER on iff == YES

---

CHANGELOG.md
lib/resolvestatus.go

This has been sporadically failing unit tests for a few weeks, likely due to changes in logging code exacerbating an already existing race condition. The race was real, and possibly affected stability of whole-cluster rectifications, or at least made them take longer in some cases.

Fix race in ResolveRecorder

---

test/smoke/matrix.go
test/smoke/matrixdef.go
test/smoke/otpl_test.go
test/smoke/paralleltestfixture.go
test/smoke/smoke_test.go
test/smoke/testbunchofsousservers.go
test/smoke/testfixture.go
test/smoke/testflags.go
test/smoke/testmain_test.go
test/smoke/testprojects.go
test/smoke/utils.go
util/testmatrix/flags.go
util/testmatrix/init.go
util/testmatrix/matrix.go
util/testmatrix/runner.go
util/testmatrix/supervisor.go

Figure this type of thing may be useful outside of sous, so cleaned up the interface a little and moved matrix-specific stuff to its own package: `utils/testmatrix`. Eventually this package should be in its own repo. A few tweaks along the way e.g. less indentation required via `Run` func, test output less nested, many renames to make it more obvious what the various things actually do.

Extract testmatrix package #trivial

---

.travis.yml
CHANGELOG.md
Makefile

We somehow skipped changelog update for 0.5.118 and 0.5.119; this PR also adds a late check that the changelog at least contains the tagged version somewhere prior to release. It's a weak check and happens late in the process. If it fails, we'll need to add a new semver tag and update the changelog to use that. Unfortunately there is nowhere earlier in the process we can detect this reliably since adding a semver tag is enough to trigger a binary release (first I considered using Danger, but that only applies to PRs not tags). Once an annotated tag is pushed it should not be changed, although I am not hardline on that in the case of failed builds, if it is changed quickly (since this is not a library we would be unlikely to break dependencies). Once any binary exists for a version in …

Release 0.5.120

---

.travis.yml

- Was trying to run 'deploy' step after every vector in the matrix.
- Now runs deploy step after 'make test-unit' only, so we get basic
checks and quick binary release.

.travis.yml: publish gh releases only once

---

CHANGELOG.md
ext/storage/postgresstatemanager_test.go
lib/map_state_to_deployments.go
server/handle_gdm.go
util/sqlgen/messages.go
util/sqlgen/messages_test.go

- Debug level logs significantly less noisy (around 50% of log volume moved to extreme level).
- SQL logs now include 'read' and 'write' in message e.g. `SQL query: read` for easier filtering.
- See CHANGELOG diff for more detail.

Logging tweaks

---

Makefile
lib/state_fixture.go
test/smoke/fixture.go

- We were needlessly telling Singularity to wait 30s
before hitting health endpoints.
- Also overall startup timeout down to 10s since it's all
tiny, local images that start immediately.

test/smoke: don't wait before starting healthchecks #trivial

---

.gitignore
.travis.yml
CHANGELOG.md
Makefile
cli/actions/server.go
graph/actions.go
graph/actions_test.go
server/handle_state_defs.go
server/server.go
test/smoke/bin.go
test/smoke/bunchofsousservers.go
test/smoke/fixture.go
test/smoke/gitclient.go
test/smoke/procman.go
test/smoke/service.go
test/smoke/sousclient.go
test/smoke/sousserver.go
test/smoke/testmain_test.go
test/smoke/utils.go
util/prefixpipe/prefixpipe.go
util/prefixpipe/prefixpipe_test.go
util/testagents/bin.go
util/testagents/flags.go
util/testagents/invocation.go
util/testagents/preparedcommand.go
util/testagents/procman.go
util/testagents/service.go
util/testmatrix/runner.go

This addresses the problem of flaky smoke tests, which was primarily caused by a sequencing error and calling `*os.Process.Wait` multiple times. Fixing that issue surfaced another one (see below), and resulted in some other changes for better logging, which needed to be fixed to get a green PR.
Test coverage is not good for this change, mostly because it modified some code that was already not coverd by unit tests (just by smoke tests). To start getting it back to a decent level, I split out 2 packages: `util/prefixpipe` and `util/testagents` in order to test those components separately. The former now has a simple test, but the latter still needs them. Since this PR is growing, I want to stop adding changes here and address test coverage and a few other things in a follow-up.
**New issue …

Fix server crash detection in smoke tests

---

cli/sous_singreqid.go
config/deploy_filter.go

- Always brings back the singularity request ID for a deployment,
whether it has been set explicitly or not.
Usage:
```sh
sous singreqid -cluster <cluster> ...other flags...
```
This is pretty rough, at minimum you need `-cluster` flag, but can explicitly set `-repo` `-flavor` `-offset` as well. Better would be a flag on `sous query gdm` to populate that field for all deployments returned, which I could do tomorrow if that's wanted.

cli: 'sous singreqid' command
