.gitignore
commands.go
commands/contracts.go
commands/server.go
deploy/contract.go
deploy/diff.go
deploy/parse.go
deploy/state.go
main.go
server/server.go
server/state.go
tools/cli/cli.go
tools/cli/progress.go
tools/cmd/cmd.go
tools/docker/container.go
tools/docker/docker.go
tools/docker/run.go
tools/git/git.go
tools/yaml/template.go
tools/yaml/template_test.go
tools/yaml/yaml_test.go

Do not merge yet. This is work towards resolving #5 
TODO:

WIP: Contracts

---

LICENSE
README.md

I think we generally converged to MIT for other OSS projects. Any objections?

Added MIT license

---

CONTRIBUTING.MD

Just a standard simple one. We can re-iterate on that in the future.
Note: I assumed we accept external contributions, but if that's not the case (even temporarily) we can change it!

Added contributing guidelines + Code of conduct

---

.travis.yml
README.md

Fixes #10 
* Requires somebody with admin rights in order to activate Travis: can I get admin rights here in github on sous OR can an admin toggle travis here? https://travis-ci.org/profile/opentable
* The test script needs a quick revision (just added the basic test command for now - not sure it is enough)

[WIP] Travis file added

---

.travis.yml

As current seems [not to work](https://github.com/opentable/sous/pull/15)

Fix no-upstream PR build (travis secret not available)

---

.travis.yml
bin/build
bin/publish
doc/architecture.md
doc/release.md

Issuing a PR because would like review here. If there's clear answers I'm missing, let's fix those before incorporating.

Add arch doc

---

README.md

I think this was the result of a linewrapping somewhere along the lines. This PR effectively just changes how some of the lines are wrapped so that some lists and code blocks format correctly.

Reformatting readme

---

.travis.yml
bin/test

putting this through as a PR fyi @nyarly

Add bin/test; exits correctly for travis

---

sous/named_version.go
sous/named_version_test.go

These just follow the commentary on a couple of recent commits...

minor style tidy-ups

---

README.md

Remove stale info from the readme and add a link to the docs directory.

Docs cleanup

---

sous/source_version.go
sous/source_version_test.go

Changes nv to sn and cn to sl

---

doc/architecture.md

Overall, I'm happy with it as is

Some little tweaks

---

sous/deployment.go
sous/deployment_diff.go
sous/deployment_diff_test.go
sous/manifest.go
sous/state.go

The diff itself runs on a collection of channels, since the eventual
desing goal is to resolve those diffs as quickly as possible.

Adding differ

---

doc/code.md
doc/maxims_and_arrows.md

Doc update

---

README.md
sous/actual_deployment_set.go
sous/deployment_builder.go
sous/image_mapping.go
sous/image_mapping_test.go
sous/rectifier.go
sous/rectifier_test.go
sous/source_version.go
util/docker_registry/client.go
util/docker_registry/raw_client.go

This also includes big extensions to the the rectifier (including a working singularity client(!)),
in particular an errors channel to report issues while rectifying.

DCOPS-7200 - NameCache is a docker manifest search

---

.gitignore
cli/config.go
cli/graph.go
cli/sous_build.go
cli/sous_init.go
cli/sous_rectify.go
cli/tests/sous_test.go
cli/user.go
lib/build.go
lib/build_test.go
lib/config.go
lib/image_mapping.go
lib/image_mapping_test.go
lib/source_version.go
lib/test/integration_test.go
util/docker_registry/dummy_client.go

Users get default configs that include an on-disk configuration file

Default config

---

.travis.yml
cli/sous.go
cli/sous_query_adc.go
cli/sous_query_gdm.go
lib/deployment.go
lib/deployment_builder.go
lib/manifest.go
lib/recti-agent.go
lib/rectifier.go
lib/resolve.go
lib/state.go
lib/test_rectification.go

Also, the -d and -v switches enable the debug and info loggers.
Finally (and this is important) deployment environment vars are now
considered when rectifying.

Added query commands

---

cli/sous_rectify.go
lib/deployment.go
lib/resolve.go

Relates to DCOPS-7553. I've been unable to manually test this since something's going awry with ADC building.

Single manifest

---

doc/cluster_and_container_iface.md

Ultimately, this should document the required interfaces and functionality of 
future container image formats, image registry and cluster services.
In the meantime, I'm hoping to address the content-addressibility issue and the 
search cache. I feel like we're at an impasse there, and I'd like to find a 
common understanding of the issues involved.

Sketch of docs about interfaces

---

util/firsterr/firsterr.go
util/firsterr/firsterr_test.go

Some work I mainly did in the evening, finished off just now to make sure `firsterr` was behaving as expected.

Firsterr tweaks

---

.gitignore
bin/check-compilation

bin/check-compilation: parallel builds

---

cli/graph.go
cli/local_config.go
cli/sous.go
ext/docker/image_mapping.go
ext/docker/logging.go
ext/singularity/logging.go
lib/assemble.go
lib/assemble_test.go
lib/deploy_config.go
lib/deploy_spec.go
lib/deployment.go
lib/logging.go
util/configloader/configloader.go
util/docker_registry/client.go
util/docker_registry/client_test.go

Holy bughunt, batman!
So: the "harvest" functionality was failing because docker's
representation because the repository name didn't have a digest or a tag
(and well it shouldn't - if it did it would be an image name...)
The Global inheritence wasn't completely impletmented.
Both now fixed with better tests and increased logging.
Would like to merge this and have Wil try it out

Not the bugfix we deserve, but the bugfix we need

---

cli/graph.go
ext/docker/builder.go
ext/docker/builder_test.go
ext/docker/dockerfile_buildpack.go
ext/git/client.go
ext/git/client_test.go
ext/git/context.go
lib/build_config.go
lib/build_config_test.go
lib/build_context.go
lib/build_manager.go
lib/buildpack.go
lib/source_context.go

Significant fixes to advisories and git client/context TECHOPS-497

---

cli/cli_test.go
cli/sous_context.go
cli/sous_init.go

Shouls improve coverage and make room to move more into DI

Adds prepared execution tests for every sous subcommand

---

cli/cli.go
cli/cli_test.go
cli/graph.go
cli/sous_query_artifacts.go
ext/docker/image_mapping.go
lib/dummy_registry.go
lib/registry.go
lib/registry_dumper.go

Trying to address Wil's current issue

Adds a command to query the build artifacts that Sous knows about

---

cli/graph.go
ext/storage/disk_state_manager.go
ext/storage/disk_state_manager_test.go
lib/deployments_generated.go
lib/manifests_generated.go
util/blueprints/cmap/cmap.go
util/blueprints/cmap/cmap_test.go
util/firsterr/firsterr.go
util/firsterr/firsterr_test.go
vendor/github.com/opentable/hy/codec.go
vendor/vendor.json

Includes #112 
Adds a parallel test for the concurrent map. Run tests with -race to make it meaningful.

Test cmap parallel

---

cli/graph.go
ext/storage/disk_state_manager.go
ext/storage/disk_state_manager_test.go
lib/deployments_generated.go
lib/manifests_generated.go
lib/source_id.go
lib/source_id_test.go
lib/source_location.go
lib/source_location_test.go
util/blueprints/cmap/cmap.go
util/blueprints/cmap/cmap_test.go
util/firsterr/firsterr.go
util/firsterr/firsterr_test.go
vendor/github.com/opentable/hy/codec.go
vendor/vendor.json

Includes #113 
Adds tests for SourceLocation, tidies up tests for SourceID.

SourceID + SourceLocation tests

---

integration/docker_helpers.go
util/test_with_docker/agents_test.go
util/test_with_docker/integration_setup.go
util/test_with_docker/local_daemon.go
util/test_with_docker/machine.go

So the upshot is that on OS X desktops, there's no password required
during a test run

Removes the sudo when run with docker-machine

---

cli/add_flags.go
cli/cli.go
cli/cli_test.go
cli/flags_otpl.go
cli/graph.go
cli/graph_sourcecontext.go
cli/graph_sourcecontext_test.go
cli/graph_targetmanifest.go
cli/graph_targetmanifest_test.go
cli/graph_test.go
cli/sous_deploy.go
cli/sous_deploy_test.go
cli/sous_init.go
cli/sous_update.go
ext/storage/disk_state_manager.go
util/cmdr/cli.go
util/cmdr/errors.go
vendor/github.com/samsalisbury/psyringe/README.md
vendor/github.com/samsalisbury/psyringe/psyringe.go
vendor/vendor.json

Includes #127 
Updates psyringe.

Psyringe cycle check

---

ext/singularity/actual_deployment_set.go

On the one hand, we were limiting the number of active
SingularityRequest capturing goroutines to the number of unique
Singularity URLs.
BUT, we were counting all the clusters and waiting for them all to
finish - so if there were two "clusters" with the same URL, (i.e.
because different deployment enviroments (ci vs. pp), one would get
skipped and never be marked `Done().`
Also handled: the stray "cannot retry: <nil>" message that popped up
because the error channel closed to indicate completion.
Finally, some extra debug logging.

Fixes a deadlock because a WaitGroup didn't decrement

---

cli/cli.go
cli/cli_test.go
ext/docker/builder.go
lib/build_config.go
lib/build_config_test.go
lib/build_result_test.go
lib/buildpack.go
util/cmdr/errors.go

Motivation was so that `sous build` would have nicer output

Adds a String() method for BuildResult

---

cli/cli.go
cli/cli_test.go
ext/docker/builder.go
ext/otpl/otpl.go
lib/build_config.go
lib/build_config_test.go
lib/build_manager.go
lib/build_result_test.go
lib/buildpack.go
lib/resolver.go
util/cmdr/errors.go

validates that tags given on the command line are formatted correctly

Adds tag validation to sous build TECHOPS-658

---

README.md
doc/deployment-workflow.md
doc/getting_started.md
doc/spinning_up.md

- Mainly to be specific about networking options satisfying OpenTable
in its current state, rather than for satisfying service discovery
in general. (Since SD has many solutions, often out-of-process.)
- Also some more detail about the Dockerfile and how it is passed
environment variables on docker run.

Getting started tweaks.

---

cli/graph.go
ext/docker/.gitignore
ext/docker/image_mapping.go
ext/docker/image_mapping_test.go

Biggest change is creation of a GroomDatabase method on NameCache.

Recreates DB when schema changes, refreshing data as needed  TECHOPS-677

---

ext/git/client.go
ext/git/client_test.go

go vet fixes in the git package. Added a unit test for instantiating Client type.

Git client go-vet fixes

---

cli/sous.go
cli/sous_server.go
cli/tests/sous_test.go
graph/graph.go
server/handle_gdm.go
server/handle_gdm_test.go
server/router.go
server/server.go
server/server_test.go
util/cmdr/help.go
vendor/github.com/julienschmidt/httprouter/LICENSE
vendor/github.com/julienschmidt/httprouter/README.md
vendor/github.com/julienschmidt/httprouter/path.go
vendor/github.com/julienschmidt/httprouter/router.go
vendor/github.com/julienschmidt/httprouter/tree.go
vendor/vendor.json

Baseline server, with first endpoint: a GDM lister TECHOPS-53

---

bin/test-lines
bin/test-stderr
bin/test-table
util/shell/shell_test.go

I'm happy to reorganize or do whatever it takes to make this Mac-friendly.

Unit tests and helper scripts for the shell package.

---

ext/git/client.go
ext/storage/git_state_manager.go
vendor/github.com/samsalisbury/psyringe/ctor.go

Would like to set up a "bleeding edge" step on their build to see if this sorts them out

Fixes for Cuisines

---

cli/sous_build.go
ext/docker/dockerfile_buildpack.go
lib/build_config.go
lib/build_config_test.go
lib/build_manager.go
lib/build_manager_test.go
util/shell/sh.go

Nota bene: while existing tests pass, and the code looks right to me,
I haven't figured out a good approach to testing the build itself,
apart from doing builds by hand

Code complete

---

ext/singularity/deployment_builder.go
ext/singularity/deployment_builder_test.go

Also adds test coverage to that function

Fix - returns nicknames to the trial request names

---

ext/singularity/deployer.go
ext/singularity/deployer_test.go

Supplants #192, rebased onto master and factoring out, adding tests for panic recovery.

Resolver panics

---

ext/storage/disk_state_manager_test.go
ext/storage/git_state_manager_test.go
ext/storage/testdata/in/manifests/github.com/opentable/sous.yaml
ext/storage/testdata/in/manifests/github.com/user/project.yaml
lib/deploy_config.go
lib/deploy_config_test.go
lib/flaw.go
lib/manifest.go
lib/resources.go
lib/resources_test.go
lib/state.go
test/http_state_manager_test.go

Require resources

---

cli/cli_test.go
cli/deploy_filter_flags.go
cli/sous_metadata.go
cli/sous_metadata_get.go
cli/sous_metadata_get_test.go
cli/sous_metadata_set.go
cli/sous_query.go
cli/sous_query_ads.go
cli/sous_update.go
ext/storage/testdata/in/defs.yaml
lib/deploy_config.go
lib/deploy_spec.go
lib/deployments.go
lib/diff_concentrator.go
lib/diff_concentrator_test.go
lib/manifest.go
lib/manifests.go
lib/map_state_to_deployments.go
lib/map_state_to_deployments_test.go
lib/state.go
util/cmdr/errors.go

The Metadata fields themselves
Scatter/gather for Global DeployConfigs
and `sous metadata get`
Hoping to add `set` before EOD

Adds metadata

---

lib/deploy_config.go
lib/deploy_config_test.go
lib/deploy_spec.go
lib/http_state_manager.go
lib/manifest.go
lib/manifest_test.go
lib/resources.go
lib/resources_test.go
lib/state.go
lib/state_test.go

This adds tests and addresses the issue where Global deployments were not being included in validations.

Bugfix: validation TECHOPS-1213

---

cli/sous_deploy.go
graph/graph.go

- Adds DryrunOption to graph for SousDeploy.
- Adds missing godoc.

Bugfix: DryrunOption

---

cli/cli.go
graph/graph.go
util/cmdr/errors.go
util/shell/command.go
util/shell/sh.go

Includes #221 
See commit message for details.

Bugfix shell output

---

doc/first-deployment-of-sous.md
examples/Dockerfile
examples/main.go
examples/sous-server.yaml

Initial draft of a "first deploy" document

---

cli/sous_server.go
ext/singularity/actual_deployment_set.go
ext/singularity/deployer.go
ext/singularity/deployer_test.go
integration/deployment_builder_test.go
integration/docker_helpers.go
integration/grafana-labels/Dockerfile
integration/hello-labels/Dockerfile
integration/hello-server-labels/Dockerfile
integration/integration_test.go
integration/test-one/Dockerfile
integration/test-three/Dockerfile
integration/test-two/Dockerfile
lib/name_resolver.go
lib/resolver.go
lib/state.go

Includes #241 
Resolves issue where sous thought requests belonged to clusters which they did not belong to.

Bugfix rectify cluster confusion

---

ext/singularity/deployment_builder.go
integration/docker_helpers.go
integration/integration_test.go

This builds on #251, removing the Skip on the multiple logical cluster test

Fix for skipped multi-cluster test

---

dev_support/sous_qa_setup/main.go
util/test_with_docker/machine.go

This was a horrible side track, see #260 for the origin of this work.

Less confusing error when docker-machine env not loaded.

---

util/test_with_docker/machine.go

This PR includes #262 and updates Godoc for re-added function, to reflect its new name and purpose. It also adds missing godoc on exported functions for the rest of the file.

Verify machine exists + docs

---

ext/storage/git_state_manager.go

- See https://github.com/opentable/sous/pull/256#pullrequestreview-13308803

storage: Add GIT_CONFIG_NOGLOBAL=true to git env.

---

cli/sous_help.go
cli/tests/sous_test.go
util/cmdr/cmdr-example/help.go
util/cmdr/help.go
util/cmdr/help_test.go

Refactored cmdr printHelp into multiple functions.

Removed recursion from cmdr printHelp

---

cli/sous_deploy.go
cli/sous_plumbing_status.go
cli/sous_query_ads.go
cli/sous_query_gdm.go
cli/sous_update.go
cli/sous_update_test.go
config/config.go
config/config_test.go
ext/docker/image_mapping_test.go
lib/auto_resolver_test.go
lib/diff_concentrator_test.go
lib/http_state_manager_test.go
lib/httpclient.go
lib/name_resolver_test.go
lib/resolvefilter.go
lib/source_location.go
lib/status_poller.go
lib/status_poller_test.go
lib/volumes_test.go
server/handle_servers.go
server/handle_servers_test.go
server/server_test.go

Accomplished here: config/serving named servers.
There's some work towards a test of the StatusPoller happy path - it's the only
test currently failing. :)
Goal would be to finish that test (mostly around constructing the right
statusJSON, I think) and confirm that the statuspoller itself works. Incidentally, constructing the JSON by hand is something of an experiment. It may be more effective simply to arrange the appropriate structs and serialize them... We lose some "does it handle incomplete or weird input" there, but I'm unsold on the value.
After that, I'd like to proceed to adding some tests for intermediate states,
making calls directly to StatusPoller/subPoller methods.

Sous status

---

.travis.yml
Makefile

This should build both Darwin and Linux binaries and create tarballs with only a subdirectory at their root.

Makefile Refinements

---

doc/sous_drives_builds.md

- Note about cross-platform builds as standard.
- Minor rewording in a couple of places.

doc: Minor edits to sous_drives_builds.md

---

README.md
doc/install.md

- Also remove duplicate material from readme.

doc: Add install.md and link from readme.

---

ext/otpl/otpl_test.go
util/filemap/filemap.go

In reply to https://github.com/opentable/sous/pull/299#discussion_r97839676 
I think this could come in handy for other integration tests especially.

util: Extract filemap.FileMap from otpl package.

---

cli/sous_deploy.go
cli/sous_plumbing_status.go
ext/git/context_test.go
graph/targetmanifest.go
lib/resolvefilter.go
lib/resolver.go
lib/source_context_test.go
lib/status_poller.go
test/projects/fail-immediately/Dockerfile

Includes #336 
`sous deploy` exits non-zero when deployment to singularity fails.

Non-zero exit code on failed deploy.

---

cli/sous_plumbing_status.go
lib/status_poller.go
lib/status_poller_test.go

'sous deploy' times out 30 minutes after successfully writing to the GDM (by way of nested 'sous plumbing status' call).

Deploy timeout

---

.travis.yml
CHANGELOG.md
lib/status_poller.go
lib/status_poller_test.go

Bug was that the "TasksStarting" state was treated as final

This fixes the bug that erroneously reported a deployment as failed

---

ext/singularity/recti-agent.go

Cast DeployHealthTimeoutSeconds to int64.

Add error handling for malformed SingularityDeploy.

---

lib/status_poller.go

Might be a bigger issue to keep an eye on

Small issue in status poller sometimes resulted in a segfault

---

.travis.yml
Makefile
integration/building_test.go

Also renamed "staticcheck" to "test-staticcheck" and made test dependent on "test-staticcheck" so that it can be run in parallel.

Restore Makefile "clean-containers" Recipe.

---

ext/storage/git_state_manager.go
ext/storage/git_state_manager_test.go

Gdm git conflict

---

ext/storage/git_state_manager_test.go

The first time I saw issues with the git strategy, it was with deletes, so I
wanted to be sure there was a test for that.

Adds a test for deleted manifests

---

.travis.yml
CHANGELOG.md
Dangerfile
Gemfile
Gemfile.lock

...I know, "like it wasn't dangerous enough already"
Danger is a Ruby tool that reviews PRs and critiques them. Specifically I'm
adding it to warn about WIP PRs and to pitch a fit about PRs without Changelog
updates.

This adds Danger to our project

---

CHANGELOG.md
cli/sous_manifest_get.go
cli/sous_manifest_set.go
cli/sous_manifest_test.go
ext/git/remote.go
ext/git/remote_test.go
lib/deploy_config.go
lib/deploy_spec.go
lib/manifest_test.go
lib/map_state_to_deployments_test.go
server/handle_manifest.go
server/handle_manifest_test.go

See changelog commit for details: https://github.com/opentable/sous/commit/d45a8a251f8d5e0e213bb136aa2044c84fbc8d01

Http update healthchecks + go1.8 compat

---

CHANGELOG.md
cli/sous_plumbing_status.go
ext/singularity/deployer.go
ext/singularity/deployer_test.go
integration/integration_test.go
lib/deploy_config.go

Closes #404 in favor of this PR

Startup options recognized as requiring deployment by singularity

---

ext/singularity/deployer_test.go

Test passes though. If this is a real problem, it exists elsewhere. Still deserves to be in the test though.

Regression test for env-vars -> new deploy #trivial

---

doc/artifact_names.md

Trying to sketch out the problem cases with names and images,
and how (I believe) advisories can help solve that issue.

Added an artifact names document

---

CHANGELOG.md
cli/sous_manifest_get.go
cli/sous_manifest_set.go
cli/sous_manifest_test.go

Manifest get set marshaling

---

ext/singularity/actual_deployment_set.go
ext/singularity/deployment_builder.go
ext/storage/git_state_manager.go

When the Singularity API changed, JSON marshalling was breaking our
history entries, which crashed rectifies.

Fixed problems parsing JSON unmarshalling

---

CHANGELOG.md
ext/storage/git_state_manager.go
server/server.go

Also make the statemanager a singleton for the server.
Ideally we need a test for singleton-ness, but currently v hard to test.

Serialise GitStateManager Read/WriteState

---

graph/graph.go
server/server_injection_test.go
vendor/github.com/samsalisbury/psyringe/README.md
vendor/github.com/samsalisbury/psyringe/ctor.go
vendor/github.com/samsalisbury/psyringe/psyringe.go
vendor/vendor.json

Ended up re-vendoring psyringe whilst working on something else. Lets see if tests pass.

experimental: Update psyringe #trivial

---

ext/docker/image_mapping.go
ext/docker/splitcontainer_buildpack.go
ext/github/sourcelocation.go
lib/source_context.go

I ran gosimple against the Sous codebase, and picked off a few easy fixes.
https://github.com/dominikh/go-tools

gosimple fixes #trivial

---

CHANGELOG.md
cli/cli_test.go
config/deploy_filter.go
config/deploy_filter_test.go
graph/sourcecontext_test.go
graph/targetmanifest.go
integration/integration_test.go
lib/resolvefilter.go
lib/resolvefilter_test.go
lib/status_poller.go
lib/status_poller_test.go

Parse in -tag with de-prefixing TECHOPS-2738

---

CHANGELOG.md
cli/cli.go
cli/sous_init.go
cli/sous_manifest.go
cli/sous_metadata.go
cli/sous_update.go
graph/graph.go
graph/testsupport.go
util/restful/client.go
util/restful/server_test.go

Adding Dryrun values to DI where needed.

---

CHANGELOG.md
graph/otpldeploy.go
graph/targetmanifest.go
graph/targetmanifest_test.go
lib/deployment.go
lib/manifest.go
lib/resolvefilter.go
util/allfields/confirmtree.go

In the past it left them empty, which caused problems.

Init sets resources

---

.gitignore

Add jetbrains files to gitignore

---

CHANGELOG.md
ext/otpl/otpl.go
ext/otpl/otpl_test.go

First foray into go so be kind!

Correctly segregate flavors when processing otpl deploy.

---

CHANGELOG.md
ext/docker/cachemessages.go
graph/local_config.go
lib/auto_resolver.go
lib/resolvecompletemessage.go
util/logging/callerinfo.go
util/logging/config.go
util/logging/config_test.go
util/logging/graphiteconfigmessage.go
util/logging/kafkaconfigurationmessage.go
util/logging/logging.go
util/logging/messages/clienthttpresponse.go
util/logging/messages/messages_test.go
util/logging/msg.go
util/logging/silentmessageerror.go
util/logging/structured.go

The core of this change is that there was a line missing to *apply* the loaded
configuration to the logging engine.
There's also a message added for the resolver loop.
Need to add to the OTLs and to add a diff reporting message.

Actually correcting Kafka configuration issues

---

CHANGELOG.md
cli/sous_manifest_test.go
graph/graph.go
integration/integration_test.go
util/logging/logging.go
util/logging/structured.go
util/restful/httpclient_test.go

We were logging what loglov3 expects as a logger-name as component-id

Change to component-id and add logger-name

---

integration/test-registry/docker-compose.yml
integration/test-registry/singularityservice/Dockerfile

integration: Update Singularity to 0.16.0

---

CHANGELOG.md
lib/resolvestate.go
lib/status_poller.go
lib/status_poller_test.go

Added a regression test, added a state to distinguish Sous API failures from deploy failures, fixed the bug.

Discovered a panic during deploy if the sous-server responds badly.

---

CHANGELOG.md
main.go

Opening this to make change more visible, will self-merge this hotfix.

Bugfix remove spew

---

graph/actions.go

Debug from yesteday was left in

Removing spew from GetUpdate #trivial

---

CHANGELOG.md
lib/debugconfig.go
lib/loggingprocessor.go
lib/loggingprocessor_test.go

When the BuildArtifact was left out, logging segfaulted.
Added a guard for nil.

Found a cause of logging panics - fixed.

---

CHANGELOG.md
cli/sous_deploy.go
cli/sous_plumbing_status.go
cli/sous_rectify.go
cli/sous_update.go
graph/actions.go
graph/actions_test.go

- Errors from injection are a normal fact of life, we shouldn't
panic for them instead returning a normal error.

graph: Do not panic in action constructors.

---

CHANGELOG.md
lib/deployment.go
lib/deployment_test.go
lib/subpoller.go

This bit us today during a real deploy.

Fix nil deploy panic

---

cli/actions/server_test.go

There appear to be 5 different tests run on the ensureGDMExists method.  Three of them dealt with a path and a git repo.  So consolidated those in one test case that has a setup loop through test cases and teardown.  Then the other two seemed unrelated and didn't need setup and teardown.

Refactor ensureGDMExists tests

---

cli/actions/server_test.go

* Rename Tests based on code review
* Fix test by file exists, so actual file exists
* Add test by dir exists

Update Test Names based off Code Review and improve tests

---

.gitignore
util/shelltest/captiveshell.go
util/shelltest/result.go
util/shelltest/shelltest.go
util/shelltest/shelltest_test.go
util/shelltest/util.go

Linter https://github.com/alecthomas/gometalinter had 19 errors, these are the commits to clear those.  Unit and Integration test after these changes.

#trivial Cleared all Lint errors produced by Linter

---

CHANGELOG.md
bin/docker_labels/main.go
graph/graph.go
integration/building_test.go
integration/deployment_builder_test.go
integration/integration_test.go
lib/resolvecompletemessage.go
util/docker_registry/client.go
util/docker_registry/client_test.go
util/docker_registry/raw_client.go
util/logging/callerinfo.go
util/logging/messages/clienthttpresponse.go
util/logging/messages/messages_test.go

See Changelog - reporting metrics for response bodies and docker registry requests.

Several fixes to metrics

---

cli/sous_config.go

add location of config.yaml to sousConfigHelp

#trivial add location of sous config

---

.gitignore
CHANGELOG.md
cli/actions/messages.go
cli/actions/update.go
util/logging/config.go
util/logging/level.go

Also fixed linting warnings
Added gitignore for debug

Loglevel allow server to continue startup with invalid log level configured

---

util/logging/level.go

updating based off PR review from @samsalisbury

#trivial updated based off PR recommendation

---

CHANGELOG.md
ext/storage/disk_state_manager.go
ext/storage/disk_state_manager_test.go

See [associated changelog entry](https://github.com/opentable/sous/compare/master...samsalisbury:always-order-owners?expand=1#diff-4ac32a78649ca5bdd8e0ba38b7006a1eR15) for details.

Bugfix: Always order owners

---

doc/build_strategies_design.md

Contrary to usual practice,
if you disagree or would like to add to the document,
please counter-PR with your changes.
We can go back and forth until we're happy,
or at least it's in an intermediate state we can tolerate.

Build strategies design doc

---

.travis.yml
CHANGELOG.md
Makefile
lib/source_location.go

Some incidental tidbits... In an attempt to keep other PRs clean and focussed, I've extracted these into their own unfocussed PR.

Grab bag: makefile and error message improvements

---

CHANGELOG.md
graph/graph.go
lib/auto_resolver.go
lib/resolve_errors_test.go
lib/resources.go
server/handle_servers.go
server/handle_status_test.go
util/logging/logging.go
util/logging/msg.go
util/logging/testsupport.go

For some cases that a particular structured message is not needed reuse of generic message in a more structured call pattern.

Generalized generic logging

---

.gitignore

workspace uses these files if attach to working folder

#trivial floobits files

---

CHANGELOG.md
ext/storage/disk_state_manager.go
lib/flaw.go
server/handle_gdm.go
server/handle_gdm_test.go

refactor handle_gdm logging so flaw message is it's own struct then reused it in new disk_state_manager structured logs

Diskmessage

---

CHANGELOG.md
cli/actions/server_test.go
graph/graph_test.go
graph/server.go
server/exchangers_test.go
server/handle_health.go
server/handle_health_test.go
server/routemap_test.go
server/server.go

Just returns 200 and the version.
Do we want to open a new ticket for DB and Singularity fields?
Or wait until they're actually something we should wait on in /health?

Simple implementation of /health endpoint

---

Dangerfile

add back the + check in front of file, not checking comment, will add that later if we really need it.

fix https://opentable.atlassian.net/browse/SOUS-874

---

vendor/github.com/mattn/go-sqlite3/README.md
vendor/github.com/mattn/go-sqlite3/backup.go
vendor/github.com/mattn/go-sqlite3/callback.go
vendor/github.com/mattn/go-sqlite3/error.go
vendor/github.com/mattn/go-sqlite3/sqlite3-binding.h
vendor/github.com/mattn/go-sqlite3/sqlite3.go
vendor/github.com/mattn/go-sqlite3/sqlite3_context.go
vendor/github.com/mattn/go-sqlite3/sqlite3_go18.go
vendor/github.com/mattn/go-sqlite3/sqlite3_icu.go
vendor/github.com/mattn/go-sqlite3/sqlite3_libsqlite3.go
vendor/github.com/mattn/go-sqlite3/sqlite3_load_extension.go
vendor/github.com/mattn/go-sqlite3/sqlite3_other.go
vendor/github.com/mattn/go-sqlite3/sqlite3_solaris.go
vendor/github.com/mattn/go-sqlite3/sqlite3_trace.go
vendor/github.com/mattn/go-sqlite3/sqlite3_type.go
vendor/github.com/mattn/go-sqlite3/sqlite3_vtable.go
vendor/github.com/mattn/go-sqlite3/sqlite3ext.h
vendor/github.com/mattn/go-sqlite3/static_mock.go
vendor/vendor.json

Let's see if there are any issues, gets rid of build warnings on mac...

#trivial vendor: upgrade sqlite3 to 696e2e4

---

CHANGELOG.md
ext/docker/selector.go
lib/build_manager.go

In response to a support request.

docker: clarify why build not possible

---

util/logging/messages/generalmsg.go

fix unit tests failing due to the sort order

#trivial force sort of keys

---

CHANGELOG.md
util/logging/kafkasink.go
util/restful/statusmiddleware.go

the objects passing in http are too large... which we should talk about seperately, it's 2 mb we are going over wire, this will eventually be too much for http protocol

fix SOUS-887

---

CHANGELOG.md
util/logging/messages/generalmsg_test.go

Some tests were broken in #614; this fixes them and adds changelog update. See https://github.com/opentable/sous/pull/614#issuecomment-369953850

Fix logging tests

---

CHANGELOG.md
ext/storage/disk_state_manager_test.go
ext/storage/postgresstatemanager_read.go
ext/storage/postgresstatemanager_test.go
ext/storage/testdata/in/manifests/github.com/opentable/sous.yaml
lib/resolvestatus.go
shell.nix

Properly loading SQL arrays

---

CHANGELOG.md
ext/storage/messages.go
ext/storage/messages_test.go
ext/storage/postgresstatemanager_read.go
ext/storage/postgresstatemanager_write.go
util/logging/interval.go

Some odd behavior in the DB needs more observability to track down.

Metrics on DB accesses

---

Makefile
ext/storage/duplexstatemanager_test.go
graph/graph.go
lib/deployment_manager.go
server/handle_single_deployment.go
server/server.go

This is as far as I got today, the commits are broken down so you may want to revert the reversions to postgres Makefile stuff in b119647e933f938e3d2d5853bb145c7aade1ddc7.

Additions to #633

---

Makefile

found couldn't build debug on mac, so split up the following make command

#trivial add darwin make

---

CHANGELOG.md
server/handle_single_deployment.go
server/handle_single_deployment_test.go
util/restful/routemap.go
util/restful/routemap_test.go

very light test, but hopefully moves us towards the polling

add the host from the request to the queueURI

---

CHANGELOG.md
ext/singularity/deployer.go
lib/r11n_queue.go
server/handle_artifact_test.go
server/handle_manifest_test.go
server/handle_r11n.go
server/handle_r11n_test.go
server/handle_single_deployment.go
server/handle_single_deployment_test.go
server/server.go
util/logging/config.go
util/logging/kafkasink.go
util/logging/logging.go
util/logging/messages.go
util/logging/messages/generalmsg.go
util/logging/messages/generalmsg_test.go
util/logging/testsupport.go
util/restful/logging.go

- Now returns DiffResolution and correct queue position.

server: /deploy-queue-item fixes

---

lib/resolver.go

#trivial lib: do not queue no-op rectifications

---

graph/graph.go

The issue was that we used the uniterpreted DeployFilterFlags instead of ResolveFilter.

Found DI dependency to set up #trivial

---

util/logging/messages.go
util/logging/messages/clienthttpresponse.go

Our existing "check what flags are defined" solution broke at some point.

More limited test for 'am testing' #trivial

---

.travis.yml
CHANGELOG.md
Makefile
ext/singularity/deployermessage_test.go
ext/singularity/diffresolutionmessage.go
ext/singularity/requeststate.go
integration/integration_test.go
lib/deployable_pair.go
lib/diff_rez_message.go
lib/diff_rez_message_test.go
lib/r11n_anomaly_message_test.go
lib/rectification.go
lib/rectification_test.go
lib/resolver.go
lib/resolvestatus.go
lib/resources.go
server/handle_single_deployment.go
util/logging/callerinfo.go
util/logging/fieldspecializations.go
util/logging/fieldspecializations_test.go
util/logging/kafkaconfigurationmessage.go
util/logging/kafkaconfigurationmessage_test.go
util/logging/messages.go
util/logging/strayfields.go
util/logging/strayfields_test.go
util/logging/structured.go

Partial fix for logging issues.

---

Dangerfile
Gemfile
Gemfile.lock
gemset.nix

Because LGTM shouldn't be NSFW

LGTM reduced to simple markdown

---

README.md

testing tc link on PR as well as writing a note about it in Readme

Add note to readme about tc links #trivial

---

Makefile

`make coverage` and `make legendary` simplified. Now use the native Go coverage tools.
N.b. output of `legendary` is a file for the `killphi/vim-legend` plugin, which
will put persistent marks in the left gutter if the file exists.

Coverage speedup #trivial

---

CHANGELOG.md
main.go

Works now, problem was exported TraceID vs traceID

Scoop the traceID to display RequestID after action run

---

Makefile

Looks like character got chopped

#trivial fix typo

---

lib/build_manager.go
lib/http_name_inserter.go

Effectively "remove debug logging" PR

No Panic, and just report errors when PUTing /artifact #trivial

---

CHANGELOG.md
ext/docker/builder.go
ext/docker/builder_test.go
ext/docker/image_mapping.go
ext/docker/image_mapping_test.go
ext/docker/indexdatabase.go
ext/docker/names.go
ext/singularity/deployer_test.go
ext/singularity/recti-agent.go
ext/singularity/rectifier_test.go
graph/graph_test.go
lib/buildpack.go
lib/deployable_chans_test.go
lib/deployable_message_test.go
lib/deployablesubmessage.go
lib/dummy_registry.go
lib/fixtures.go
lib/http_name_inserter.go
lib/http_name_inserter_test.go
lib/registry.go
lib/registry_dumper.go
lib/resolver_test.go
server/handle_artifact.go
server/handle_artifact_test.go
server/testsupport.go
util/logging/ergonomics.go

Also, sous build now reports to this endpoint correctly.

Restores the PUT /artifact endpoint.

---

CHANGELOG.md
ext/docker/buildutil.go
ext/docker/dockerfile_buildpack.go
ext/docker/runmount_builder.go
ext/docker/runmount_builder_test.go
ext/docker/splitcontainer_runnablebuilder.go
ext/docker/splitcontainer_splitbuilder.go
ext/docker/splitcontainer_splitbuilder_test.go

Replace flaky regexes with local uuid tags

---

CHANGELOG.md
cli/actions/deploy.go
ext/singularity/deployer.go
server/handle_single_deployment.go
server/handle_single_deployment_test.go

recreated to get around github problem. applied some of sam's changes.

Sous 1011 singularity link

---

Jenkinsfile

Added the static tests as well.

Add static tests #trivial

---

Gemfile.lock

as instructed ran bundle update fpm, then ran a make deb-build, looked like it worked.

update Gemfile.lock with newer fpm

---

test/smoke/bin.go
test/smoke/smoke_test.go
test/smoke/utils.go

Tidying up loose ends whilst adding tests for SOUS-1020. This may speed up running smoke tests.

smoketest tidy up #trivial

---

.travis.yml
CHANGELOG.md
lib/resolvefilter.go
lib/resolvefilter_test.go
test/smoke/bugs_test.go
test/smoke/smoke_test.go

Resolves SOUS-1020; includes #804; See https://github.com/opentable/sous/pull/805/files#diff-91432d762aa99853969261d3158edbb4R15 for test case covering the bug report, and https://github.com/opentable/sous/pull/805/commits/e13914ca4845dc165bbe1da6887be4c8e7f07aac for the resolution.

Corrects confusing error message when manifest not found

---

.gitignore
CHANGELOG.md
ext/docker/builder.go
ext/docker/builder_test.go
ext/docker/image_mapping.go
ext/docker/image_mapping_test.go
ext/docker/names.go
ext/docker/names_test.go
lib/source_id.go
test/smoke/bugs_test.go
test/smoke/gitclient.go
test/smoke/projects.go

Includes #805 to avoid merge conflicts. See changelog diff for details.

Bugfix docker ref casing

---

cli/sous_init.go
cli/tests/sous_test.go

added further kind flag checks
added tests to kind flag different scenarios

added further flag checks to sous init

---

doc/manifest_format.md

This is not currently supported and confusing for people viewing the doc.

docs: Remove sous-jenkins metadata #trivial

---

.travis.yml
Makefile
cli/queries/deployment_filters.go

Fingers crossed this doesn't have the same Travis fate as #831 and #832...

Update to go1.11.5 #trivial
